doctrine:
    dbal:
        default_connection: default
        url: '%env(DATABASE_URL)%'
        charset: UTF8
        logging: true
        mapping_types:
            enum: string
#        wrapper_class: SuppCore\AdministrativoBackend\Doctrine\DBAL\Wrappers\ConnectionWrapper
        use_savepoints: true
    orm:
        dql:
            numeric_functions:
                round: SuppCore\AdministrativoBackend\DQL\Round
                money: SuppCore\AdministrativoBackend\DQL\Money
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        controller_resolver:
            auto_mapping: false
        report_fields_where_declared: true
        enable_lazy_ghost_objects: true
        metadata_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: pool
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: pool
            pool: doctrine.result_cache_pool
        filters:
            softdeleteable:
                class: 'Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter'
                enabled: true
            pcu:
                class: 'SuppCore\AdministrativoBackend\Doctrine\ORM\Pcu\PcuFilter'
                enabled: false
        mappings:
            supp_core.administrativo_backend:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: SuppCore\AdministrativoBackend\Entity\
                alias: SuppCoreAdministrativoBackend
            gedmo_loggable:
                type: attribute
                prefix: Gedmo\Loggable\Entity
                dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity'
                alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_tree:
                type: attribute
                prefix: Gedmo\Tree\Entity
                dir: '%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity'
                alias: GedmoTree # this one is optional and will default to the name set for the mapping
                is_bundle: false
            supp_core.consultivo_backend:
                is_bundle: false
                type: attribute
                dir: "%kernel.project_dir%/vendor/supp-core/supp-consultivo-backend/src/Entity"
                prefix: 'SuppCore\ConsultivoBackend\Entity\'
                alias: SuppCoreConsultivoBackend
            supp_core.disciplinar_backend:
                is_bundle: false
                type: attribute
                dir: "%kernel.project_dir%/vendor/supp-core/supp-disciplinar-backend/src/Entity"
                prefix: 'SuppCore\DisciplinarBackend\Entity\'
                alias: SuppCoreDisciplinarBackend
            supp_core.ecarta_backend:
                is_bundle: false
                type: attribute
                dir: "%kernel.project_dir%/vendor/supp-core/supp-ecarta-backend/src/Entity"
                prefix: 'SuppCore\EcartaBackend\Entity\'
                alias: SuppCoreEcartaBackend
            supp_core.judicial_backend:
                is_bundle: false
                type: attribute
                dir: "%kernel.project_dir%/vendor/supp-core/supp-judicial-backend/src/Entity"
                prefix: 'SuppCore\JudicialBackend\Entity\'
                alias: SuppCoreJudicialBackend
            supp_core.gestao_devedor_backend:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/vendor/supp-core/supp-gestao-devedor-backend/src/Entity'
                prefix: SuppCore\GestaoDevedorBackend\Entity\
                alias: SuppCoreGestaoDevedorBackend
            supp_core.receita_federal_backend:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/vendor/supp-core/supp-receita-federal-backend/src/Entity'
                prefix: SuppCore\ReceitaFederalBackend\Entity\
                alias: SuppCoreReceitaFederalBackend
