# See docs https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    rate_limiter:
        per_user:
            policy: 'sliding_window'
            limit: 1200
            interval: '15 minutes'
            cache_pool: 'rate_limiter.cache'
        per_api:
            policy: 'sliding_window'
            limit: 7200
            interval: '15 minutes'
            cache_pool: 'rate_limiter.cache'
        per_api_night:
            policy: 'sliding_window'
            limit: 35000
            interval: '15 minutes'
            cache_pool: 'rate_limiter.cache'
