<?php

declare(strict_types=1);

namespace SuppCore\AdministrativoBackend\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240223223521Disciplinar extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'migration from 1.14.0 to 1.15.0';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        if ('oracle' === $this->connection->getDatabasePlatform()->getName() ||
            'postgresql' === $this->connection->getDatabasePlatform()->getName()) {
            $this->addSql('CREATE SEQUENCE dc_classe_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE dc_especie_fase_disciplinar_id START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE dc_fase_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE dc_impedimento_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE dc_membro_comissao_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE dc_mod_iniciativa_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE dc_mod_situacao_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE dc_motivo_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE dc_motivo_causa_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE dc_origem_representacao_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE dc_processo_juizo_admiss_id_se START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE dc_processo_juizo_admiss_res_i START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE dc_processo_pad_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE dc_resultado_juizo_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE dc_setor_responsavel_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE dc_unidade_relacionada_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');

            $this->addSql('CREATE TABLE dc_classe (id NUMBER(10) NOT NULL, parent_id NUMBER(10) DEFAULT NULL NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, nm_classe VARCHAR2(255) NOT NULL, lft NUMBER(10) NOT NULL, lvl NUMBER(10) NOT NULL, rgt NUMBER(10) NOT NULL, root NUMBER(10) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_523AE435D17F50A6 ON dc_classe (uuid)');
            $this->addSql('CREATE INDEX IDX_523AE435727ACA70 ON dc_classe (parent_id)');
            $this->addSql('CREATE INDEX IDX_523AE435F69C7D9B ON dc_classe (criado_por)');
            $this->addSql('CREATE INDEX IDX_523AE435AF2B1A92 ON dc_classe (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_523AE435A395BB94 ON dc_classe (apagado_por)');
            $this->addSql('COMMENT ON COLUMN dc_classe.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE dc_especie_fase_disciplinar (id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, nm_especie VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_ADEAE831D17F50A6 ON dc_especie_fase_disciplinar (uuid)');
            $this->addSql('CREATE INDEX IDX_ADEAE831F69C7D9B ON dc_especie_fase_disciplinar (criado_por)');
            $this->addSql('CREATE INDEX IDX_ADEAE831AF2B1A92 ON dc_especie_fase_disciplinar (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_ADEAE831A395BB94 ON dc_especie_fase_disciplinar (apagado_por)');
            $this->addSql('COMMENT ON COLUMN dc_especie_fase_disciplinar.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE dc_fase (id NUMBER(10) NOT NULL, especies_fases_disciplinar_id NUMBER(10) NOT NULL, processo_id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, dt_final TIMESTAMP(0) DEFAULT NULL NULL, dt_inicio TIMESTAMP(0) NOT NULL, ds_justificativa VARCHAR2(255) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_B824244CD17F50A6 ON dc_fase (uuid)');
            $this->addSql('CREATE INDEX IDX_B824244C8010FB26 ON dc_fase (especies_fases_disciplinar_id)');
            $this->addSql('CREATE INDEX IDX_B824244CAAA822D2 ON dc_fase (processo_id)');
            $this->addSql('CREATE INDEX IDX_B824244CF69C7D9B ON dc_fase (criado_por)');
            $this->addSql('CREATE INDEX IDX_B824244CAF2B1A92 ON dc_fase (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_B824244CA395BB94 ON dc_fase (apagado_por)');
            $this->addSql('COMMENT ON COLUMN dc_fase.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE dc_impedimento (id NUMBER(10) NOT NULL, usuario_id NUMBER(10) NOT NULL, processo_id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, ds_funcao_confianca VARCHAR2(255) DEFAULT NULL NULL, ds_observacao_impedimento VARCHAR2(255) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_377BE4D7D17F50A6 ON dc_impedimento (uuid)');
            $this->addSql('CREATE INDEX IDX_377BE4D7DB38439E ON dc_impedimento (usuario_id)');
            $this->addSql('CREATE INDEX IDX_377BE4D7AAA822D2 ON dc_impedimento (processo_id)');
            $this->addSql('CREATE INDEX IDX_377BE4D7F69C7D9B ON dc_impedimento (criado_por)');
            $this->addSql('CREATE INDEX IDX_377BE4D7AF2B1A92 ON dc_impedimento (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_377BE4D7A395BB94 ON dc_impedimento (apagado_por)');
            $this->addSql('COMMENT ON COLUMN dc_impedimento.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE dc_membro_comissao (id NUMBER(10) NOT NULL, processo_id NUMBER(10) NOT NULL, usuario_id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, dt_inicio TIMESTAMP(0) NOT NULL, dt_encerramento TIMESTAMP(0) DEFAULT NULL NULL, in_funcao_exercida VARCHAR2(255) NOT NULL, tx_matricula_siape VARCHAR2(255) NOT NULL, tx_observacao VARCHAR2(255) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_7001BA03D17F50A6 ON dc_membro_comissao (uuid)');
            $this->addSql('CREATE INDEX IDX_7001BA03AAA822D2 ON dc_membro_comissao (processo_id)');
            $this->addSql('CREATE INDEX IDX_7001BA03DB38439E ON dc_membro_comissao (usuario_id)');
            $this->addSql('CREATE INDEX IDX_7001BA03F69C7D9B ON dc_membro_comissao (criado_por)');
            $this->addSql('CREATE INDEX IDX_7001BA03AF2B1A92 ON dc_membro_comissao (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_7001BA03A395BB94 ON dc_membro_comissao (apagado_por)');
            $this->addSql('COMMENT ON COLUMN dc_membro_comissao.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE dc_mod_iniciativa (id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, valor VARCHAR2(255) DEFAULT NULL NULL, descricao VARCHAR2(255) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, ativo NUMBER(1) NOT NULL, uuid CHAR(36) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_76A7C1FB2E892728 ON dc_mod_iniciativa (valor)');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_76A7C1FBD17F50A6 ON dc_mod_iniciativa (uuid)');
            $this->addSql('CREATE INDEX IDX_76A7C1FBF69C7D9B ON dc_mod_iniciativa (criado_por)');
            $this->addSql('CREATE INDEX IDX_76A7C1FBAF2B1A92 ON dc_mod_iniciativa (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_76A7C1FBA395BB94 ON dc_mod_iniciativa (apagado_por)');
            $this->addSql('COMMENT ON COLUMN dc_mod_iniciativa.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE dc_mod_situacao (id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, valor VARCHAR2(255) DEFAULT NULL NULL, descricao VARCHAR2(255) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, ativo NUMBER(1) NOT NULL, uuid CHAR(36) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_347132792E892728 ON dc_mod_situacao (valor)');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_34713279D17F50A6 ON dc_mod_situacao (uuid)');
            $this->addSql('CREATE INDEX IDX_34713279F69C7D9B ON dc_mod_situacao (criado_por)');
            $this->addSql('CREATE INDEX IDX_34713279AF2B1A92 ON dc_mod_situacao (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_34713279A395BB94 ON dc_mod_situacao (apagado_por)');
            $this->addSql('COMMENT ON COLUMN dc_mod_situacao.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE dc_motivo (id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, in_tipo VARCHAR2(255) NOT NULL, nm_motivo VARCHAR2(255) NOT NULL, num_dias_prazo NUMBER(10) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_C44463C5D17F50A6 ON dc_motivo (uuid)');
            $this->addSql('CREATE INDEX IDX_C44463C5F69C7D9B ON dc_motivo (criado_por)');
            $this->addSql('CREATE INDEX IDX_C44463C5AF2B1A92 ON dc_motivo (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_C44463C5A395BB94 ON dc_motivo (apagado_por)');
            $this->addSql('COMMENT ON COLUMN dc_motivo.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE dc_motivo_causa (id NUMBER(10) NOT NULL, motivo_id NUMBER(10) NOT NULL, processo_id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, in_causa VARCHAR2(255) NOT NULL, dt_inicio TIMESTAMP(0) NOT NULL, dt_fim DATE DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_60E82456D17F50A6 ON dc_motivo_causa (uuid)');
            $this->addSql('CREATE INDEX IDX_60E82456F9E584F8 ON dc_motivo_causa (motivo_id)');
            $this->addSql('CREATE INDEX IDX_60E82456AAA822D2 ON dc_motivo_causa (processo_id)');
            $this->addSql('CREATE INDEX IDX_60E82456F69C7D9B ON dc_motivo_causa (criado_por)');
            $this->addSql('CREATE INDEX IDX_60E82456AF2B1A92 ON dc_motivo_causa (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_60E82456A395BB94 ON dc_motivo_causa (apagado_por)');
            $this->addSql('COMMENT ON COLUMN dc_motivo_causa.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE dc_origem_representacao (id NUMBER(10) NOT NULL, parent_id NUMBER(10) DEFAULT NULL NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, nm_orgao VARCHAR2(255) DEFAULT NULL NULL, lft NUMBER(10) NOT NULL, lvl NUMBER(10) NOT NULL, rgt NUMBER(10) NOT NULL, root NUMBER(10) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_BFAD9750D17F50A6 ON dc_origem_representacao (uuid)');
            $this->addSql('CREATE INDEX IDX_BFAD9750727ACA70 ON dc_origem_representacao (parent_id)');
            $this->addSql('CREATE INDEX IDX_BFAD9750F69C7D9B ON dc_origem_representacao (criado_por)');
            $this->addSql('CREATE INDEX IDX_BFAD9750AF2B1A92 ON dc_origem_representacao (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_BFAD9750A395BB94 ON dc_origem_representacao (apagado_por)');
            $this->addSql('COMMENT ON COLUMN dc_origem_representacao.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE dc_processo_juizo_admiss (id NUMBER(10) NOT NULL, processo_id NUMBER(10) NOT NULL, mod_situacao_id NUMBER(10) DEFAULT NULL NULL, origem_representacao_id NUMBER(10) NOT NULL, mod_iniciativa_id NUMBER(10) NOT NULL, cd_classe NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, in_juizo_admissibilidade NUMBER(1) DEFAULT NULL NULL, dt_recebimento_orgao TIMESTAMP(0) NOT NULL, dt_cadastro TIMESTAMP(0) DEFAULT NULL NULL, dt_conhecimento_admin TIMESTAMP(0) DEFAULT NULL NULL, dt_conhecimento_autorid TIMESTAMP(0) DEFAULT NULL NULL, dt_conclusao TIMESTAMP(0) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, dt_est_advertencia TIMESTAMP(0) DEFAULT NULL NULL, dt_est_suspensao TIMESTAMP(0) DEFAULT NULL NULL, dt_est_demissao TIMESTAMP(0) DEFAULT NULL NULL, num_tempo_transcorrido NUMBER(10) DEFAULT NULL NULL, dt_ultima_suspensao TIMESTAMP(0) DEFAULT NULL NULL, num_dias_suspensos NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_73BB79A5D17F50A6 ON dc_processo_juizo_admiss (uuid)');
            $this->addSql('CREATE INDEX IDX_73BB79A5AAA822D2 ON dc_processo_juizo_admiss (processo_id)');
            $this->addSql('CREATE INDEX IDX_73BB79A5CD74F328 ON dc_processo_juizo_admiss (mod_situacao_id)');
            $this->addSql('CREATE INDEX IDX_73BB79A5A4011EBA ON dc_processo_juizo_admiss (origem_representacao_id)');
            $this->addSql('CREATE INDEX IDX_73BB79A548DB6CC2 ON dc_processo_juizo_admiss (mod_iniciativa_id)');
            $this->addSql('CREATE INDEX IDX_73BB79A53C9E80E5 ON dc_processo_juizo_admiss (cd_classe)');
            $this->addSql('CREATE INDEX IDX_73BB79A5F69C7D9B ON dc_processo_juizo_admiss (criado_por)');
            $this->addSql('CREATE INDEX IDX_73BB79A5AF2B1A92 ON dc_processo_juizo_admiss (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_73BB79A5A395BB94 ON dc_processo_juizo_admiss (apagado_por)');
            $this->addSql('COMMENT ON COLUMN dc_processo_juizo_admiss.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE dc_processo_juizo_admiss_res (id NUMBER(10) NOT NULL, processo_id NUMBER(10) NOT NULL, resultado_juizo_id NUMBER(10) NOT NULL, pessoa_id NUMBER(10) DEFAULT NULL NULL, setor_id NUMBER(10) DEFAULT NULL NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, dt_resultado TIMESTAMP(0) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_DB712EAFD17F50A6 ON dc_processo_juizo_admiss_res (uuid)');
            $this->addSql('CREATE INDEX IDX_DB712EAFAAA822D2 ON dc_processo_juizo_admiss_res (processo_id)');
            $this->addSql('CREATE INDEX IDX_DB712EAF74A6EA2D ON dc_processo_juizo_admiss_res (resultado_juizo_id)');
            $this->addSql('CREATE INDEX IDX_DB712EAFDF6FA0A5 ON dc_processo_juizo_admiss_res (pessoa_id)');
            $this->addSql('CREATE INDEX IDX_DB712EAF4D94F126 ON dc_processo_juizo_admiss_res (setor_id)');
            $this->addSql('CREATE INDEX IDX_DB712EAFF69C7D9B ON dc_processo_juizo_admiss_res (criado_por)');
            $this->addSql('CREATE INDEX IDX_DB712EAFAF2B1A92 ON dc_processo_juizo_admiss_res (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_DB712EAFA395BB94 ON dc_processo_juizo_admiss_res (apagado_por)');
            $this->addSql('COMMENT ON COLUMN dc_processo_juizo_admiss_res.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE dc_processo_pad (id NUMBER(10) NOT NULL, processo_id NUMBER(10) NOT NULL, processo_juizo_admiss_id NUMBER(10) DEFAULT NULL NULL, mod_situacao_id NUMBER(10) DEFAULT NULL NULL, cd_classe NUMBER(10) NOT NULL, municipios_id NUMBER(10) NOT NULL, origem_representacao_id NUMBER(10) DEFAULT NULL NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, dt_conhecimento_admin TIMESTAMP(0) DEFAULT NULL NULL, dt_conhecimento_autoridade TIMESTAMP(0) NOT NULL, dt_alteracao TIMESTAMP(0) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, dt_est_advertencia TIMESTAMP(0) DEFAULT NULL NULL, dt_est_suspensao TIMESTAMP(0) DEFAULT NULL NULL, dt_est_demissao TIMESTAMP(0) DEFAULT NULL NULL, num_tempo_transcorrido NUMBER(10) DEFAULT NULL NULL, dt_ultima_suspensao TIMESTAMP(0) DEFAULT NULL NULL, num_dias_suspensos NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_24289012D17F50A6 ON dc_processo_pad (uuid)');
            $this->addSql('CREATE INDEX IDX_24289012AAA822D2 ON dc_processo_pad (processo_id)');
            $this->addSql('CREATE INDEX IDX_24289012653515F8 ON dc_processo_pad (processo_juizo_admiss_id)');
            $this->addSql('CREATE INDEX IDX_24289012CD74F328 ON dc_processo_pad (mod_situacao_id)');
            $this->addSql('CREATE INDEX IDX_242890123C9E80E5 ON dc_processo_pad (cd_classe)');
            $this->addSql('CREATE INDEX IDX_242890124723E346 ON dc_processo_pad (municipios_id)');
            $this->addSql('CREATE INDEX IDX_24289012A4011EBA ON dc_processo_pad (origem_representacao_id)');
            $this->addSql('CREATE INDEX IDX_24289012F69C7D9B ON dc_processo_pad (criado_por)');
            $this->addSql('CREATE INDEX IDX_24289012AF2B1A92 ON dc_processo_pad (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_24289012A395BB94 ON dc_processo_pad (apagado_por)');
            $this->addSql('COMMENT ON COLUMN dc_processo_pad.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE dc_resultado_juizo (id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, nm_resultado VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_A8CA1D5D17F50A6 ON dc_resultado_juizo (uuid)');
            $this->addSql('CREATE INDEX IDX_A8CA1D5F69C7D9B ON dc_resultado_juizo (criado_por)');
            $this->addSql('CREATE INDEX IDX_A8CA1D5AF2B1A92 ON dc_resultado_juizo (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_A8CA1D5A395BB94 ON dc_resultado_juizo (apagado_por)');
            $this->addSql('COMMENT ON COLUMN dc_resultado_juizo.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE dc_setor_responsavel (id NUMBER(10) NOT NULL, setor_id NUMBER(10) NOT NULL, processo_id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, dt_designacao TIMESTAMP(0) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_F84BED22D17F50A6 ON dc_setor_responsavel (uuid)');
            $this->addSql('CREATE INDEX IDX_F84BED224D94F126 ON dc_setor_responsavel (setor_id)');
            $this->addSql('CREATE INDEX IDX_F84BED22AAA822D2 ON dc_setor_responsavel (processo_id)');
            $this->addSql('CREATE INDEX IDX_F84BED22F69C7D9B ON dc_setor_responsavel (criado_por)');
            $this->addSql('CREATE INDEX IDX_F84BED22AF2B1A92 ON dc_setor_responsavel (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_F84BED22A395BB94 ON dc_setor_responsavel (apagado_por)');
            $this->addSql('COMMENT ON COLUMN dc_setor_responsavel.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE dc_unidade_relacionada (id NUMBER(10) NOT NULL, setor_id NUMBER(10) NOT NULL, processo_id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_6350141CD17F50A6 ON dc_unidade_relacionada (uuid)');
            $this->addSql('CREATE INDEX IDX_6350141C4D94F126 ON dc_unidade_relacionada (setor_id)');
            $this->addSql('CREATE INDEX IDX_6350141CAAA822D2 ON dc_unidade_relacionada (processo_id)');
            $this->addSql('CREATE INDEX IDX_6350141CF69C7D9B ON dc_unidade_relacionada (criado_por)');
            $this->addSql('CREATE INDEX IDX_6350141CAF2B1A92 ON dc_unidade_relacionada (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_6350141CA395BB94 ON dc_unidade_relacionada (apagado_por)');
            $this->addSql('COMMENT ON COLUMN dc_unidade_relacionada.uuid IS \'(DC2Type:guid)\'');

            $this->addSql('ALTER TABLE dc_classe ADD CONSTRAINT FK_523AE435727ACA70 FOREIGN KEY (parent_id) REFERENCES dc_classe (id) ON DELETE SET NULL');
            $this->addSql('ALTER TABLE dc_classe ADD CONSTRAINT FK_523AE435F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_classe ADD CONSTRAINT FK_523AE435AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_classe ADD CONSTRAINT FK_523AE435A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_especie_fase_disciplinar ADD CONSTRAINT FK_ADEAE831F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_especie_fase_disciplinar ADD CONSTRAINT FK_ADEAE831AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_especie_fase_disciplinar ADD CONSTRAINT FK_ADEAE831A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_fase ADD CONSTRAINT FK_B824244C8010FB26 FOREIGN KEY (especies_fases_disciplinar_id) REFERENCES dc_especie_fase_disciplinar (id)');
            $this->addSql('ALTER TABLE dc_fase ADD CONSTRAINT FK_B824244CAAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_fase ADD CONSTRAINT FK_B824244CF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_fase ADD CONSTRAINT FK_B824244CAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_fase ADD CONSTRAINT FK_B824244CA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_impedimento ADD CONSTRAINT FK_377BE4D7DB38439E FOREIGN KEY (usuario_id) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_impedimento ADD CONSTRAINT FK_377BE4D7AAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_impedimento ADD CONSTRAINT FK_377BE4D7F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_impedimento ADD CONSTRAINT FK_377BE4D7AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_impedimento ADD CONSTRAINT FK_377BE4D7A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_membro_comissao ADD CONSTRAINT FK_7001BA03AAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_membro_comissao ADD CONSTRAINT FK_7001BA03DB38439E FOREIGN KEY (usuario_id) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_membro_comissao ADD CONSTRAINT FK_7001BA03F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_membro_comissao ADD CONSTRAINT FK_7001BA03AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_membro_comissao ADD CONSTRAINT FK_7001BA03A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_mod_iniciativa ADD CONSTRAINT FK_76A7C1FBF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_mod_iniciativa ADD CONSTRAINT FK_76A7C1FBAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_mod_iniciativa ADD CONSTRAINT FK_76A7C1FBA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_mod_situacao ADD CONSTRAINT FK_34713279F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_mod_situacao ADD CONSTRAINT FK_34713279AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_mod_situacao ADD CONSTRAINT FK_34713279A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_motivo ADD CONSTRAINT FK_C44463C5F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_motivo ADD CONSTRAINT FK_C44463C5AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_motivo ADD CONSTRAINT FK_C44463C5A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_motivo_causa ADD CONSTRAINT FK_60E82456F9E584F8 FOREIGN KEY (motivo_id) REFERENCES dc_motivo (id)');
            $this->addSql('ALTER TABLE dc_motivo_causa ADD CONSTRAINT FK_60E82456AAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_motivo_causa ADD CONSTRAINT FK_60E82456F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_motivo_causa ADD CONSTRAINT FK_60E82456AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_motivo_causa ADD CONSTRAINT FK_60E82456A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_origem_representacao ADD CONSTRAINT FK_BFAD9750727ACA70 FOREIGN KEY (parent_id) REFERENCES dc_origem_representacao (id) ON DELETE SET NULL');
            $this->addSql('ALTER TABLE dc_origem_representacao ADD CONSTRAINT FK_BFAD9750F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_origem_representacao ADD CONSTRAINT FK_BFAD9750AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_origem_representacao ADD CONSTRAINT FK_BFAD9750A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss ADD CONSTRAINT FK_73BB79A5AAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss ADD CONSTRAINT FK_73BB79A5CD74F328 FOREIGN KEY (mod_situacao_id) REFERENCES dc_mod_situacao (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss ADD CONSTRAINT FK_73BB79A5A4011EBA FOREIGN KEY (origem_representacao_id) REFERENCES dc_origem_representacao (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss ADD CONSTRAINT FK_73BB79A548DB6CC2 FOREIGN KEY (mod_iniciativa_id) REFERENCES dc_mod_iniciativa (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss ADD CONSTRAINT FK_73BB79A53C9E80E5 FOREIGN KEY (cd_classe) REFERENCES dc_classe (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss ADD CONSTRAINT FK_73BB79A5F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss ADD CONSTRAINT FK_73BB79A5AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss ADD CONSTRAINT FK_73BB79A5A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res ADD CONSTRAINT FK_DB712EAFAAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res ADD CONSTRAINT FK_DB712EAF74A6EA2D FOREIGN KEY (resultado_juizo_id) REFERENCES dc_resultado_juizo (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res ADD CONSTRAINT FK_DB712EAFDF6FA0A5 FOREIGN KEY (pessoa_id) REFERENCES ad_pessoa (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res ADD CONSTRAINT FK_DB712EAF4D94F126 FOREIGN KEY (setor_id) REFERENCES ad_setor (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res ADD CONSTRAINT FK_DB712EAFF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res ADD CONSTRAINT FK_DB712EAFAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res ADD CONSTRAINT FK_DB712EAFA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_24289012AAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_24289012653515F8 FOREIGN KEY (processo_juizo_admiss_id) REFERENCES dc_processo_juizo_admiss (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_24289012CD74F328 FOREIGN KEY (mod_situacao_id) REFERENCES dc_mod_situacao (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_242890123C9E80E5 FOREIGN KEY (cd_classe) REFERENCES dc_classe (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_242890124723E346 FOREIGN KEY (municipios_id) REFERENCES ad_municipio (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_24289012A4011EBA FOREIGN KEY (origem_representacao_id) REFERENCES dc_origem_representacao (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_24289012F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_24289012AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_24289012A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_resultado_juizo ADD CONSTRAINT FK_A8CA1D5F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_resultado_juizo ADD CONSTRAINT FK_A8CA1D5AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_resultado_juizo ADD CONSTRAINT FK_A8CA1D5A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_setor_responsavel ADD CONSTRAINT FK_F84BED224D94F126 FOREIGN KEY (setor_id) REFERENCES ad_setor (id)');
            $this->addSql('ALTER TABLE dc_setor_responsavel ADD CONSTRAINT FK_F84BED22AAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_setor_responsavel ADD CONSTRAINT FK_F84BED22F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_setor_responsavel ADD CONSTRAINT FK_F84BED22AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_setor_responsavel ADD CONSTRAINT FK_F84BED22A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_unidade_relacionada ADD CONSTRAINT FK_6350141C4D94F126 FOREIGN KEY (setor_id) REFERENCES ad_setor (id)');
            $this->addSql('ALTER TABLE dc_unidade_relacionada ADD CONSTRAINT FK_6350141CAAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_unidade_relacionada ADD CONSTRAINT FK_6350141CF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_unidade_relacionada ADD CONSTRAINT FK_6350141CAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_unidade_relacionada ADD CONSTRAINT FK_6350141CA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');

        } else {

            $this->addSql('CREATE TABLE dc_classe (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, criado_por INT DEFAULT NULL, atualizado_por INT DEFAULT NULL, apagado_por INT DEFAULT NULL, nm_classe VARCHAR(255) NOT NULL, lft INT NOT NULL, lvl INT NOT NULL, rgt INT NOT NULL, root INT DEFAULT NULL, criado_em DATETIME DEFAULT NULL, atualizado_em DATETIME DEFAULT NULL, apagado_em DATETIME DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', UNIQUE INDEX UNIQ_523AE435D17F50A6 (uuid), INDEX IDX_523AE435727ACA70 (parent_id), INDEX IDX_523AE435F69C7D9B (criado_por), INDEX IDX_523AE435AF2B1A92 (atualizado_por), INDEX IDX_523AE435A395BB94 (apagado_por), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dc_especie_fase_disciplinar (id INT AUTO_INCREMENT NOT NULL, criado_por INT DEFAULT NULL, atualizado_por INT DEFAULT NULL, apagado_por INT DEFAULT NULL, nm_especie VARCHAR(255) NOT NULL, criado_em DATETIME DEFAULT NULL, atualizado_em DATETIME DEFAULT NULL, apagado_em DATETIME DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', UNIQUE INDEX UNIQ_ADEAE831D17F50A6 (uuid), INDEX IDX_ADEAE831F69C7D9B (criado_por), INDEX IDX_ADEAE831AF2B1A92 (atualizado_por), INDEX IDX_ADEAE831A395BB94 (apagado_por), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dc_fase (id INT AUTO_INCREMENT NOT NULL, especies_fases_disciplinar_id INT NOT NULL, processo_id INT NOT NULL, criado_por INT DEFAULT NULL, atualizado_por INT DEFAULT NULL, apagado_por INT DEFAULT NULL, dt_final DATETIME DEFAULT NULL, dt_inicio DATETIME NOT NULL, ds_justificativa VARCHAR(255) DEFAULT NULL, criado_em DATETIME DEFAULT NULL, atualizado_em DATETIME DEFAULT NULL, apagado_em DATETIME DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', UNIQUE INDEX UNIQ_B824244CD17F50A6 (uuid), INDEX IDX_B824244C8010FB26 (especies_fases_disciplinar_id), INDEX IDX_B824244CAAA822D2 (processo_id), INDEX IDX_B824244CF69C7D9B (criado_por), INDEX IDX_B824244CAF2B1A92 (atualizado_por), INDEX IDX_B824244CA395BB94 (apagado_por), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dc_impedimento (id INT AUTO_INCREMENT NOT NULL, usuario_id INT NOT NULL, processo_id INT NOT NULL, criado_por INT DEFAULT NULL, atualizado_por INT DEFAULT NULL, apagado_por INT DEFAULT NULL, ds_funcao_confianca VARCHAR(255) DEFAULT NULL, ds_observacao_impedimento VARCHAR(255) DEFAULT NULL, criado_em DATETIME DEFAULT NULL, atualizado_em DATETIME DEFAULT NULL, apagado_em DATETIME DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', UNIQUE INDEX UNIQ_377BE4D7D17F50A6 (uuid), INDEX IDX_377BE4D7DB38439E (usuario_id), INDEX IDX_377BE4D7AAA822D2 (processo_id), INDEX IDX_377BE4D7F69C7D9B (criado_por), INDEX IDX_377BE4D7AF2B1A92 (atualizado_por), INDEX IDX_377BE4D7A395BB94 (apagado_por), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dc_membro_comissao (id INT AUTO_INCREMENT NOT NULL, processo_id INT NOT NULL, usuario_id INT NOT NULL, criado_por INT DEFAULT NULL, atualizado_por INT DEFAULT NULL, apagado_por INT DEFAULT NULL, dt_inicio DATETIME NOT NULL, dt_encerramento DATETIME DEFAULT NULL, in_funcao_exercida VARCHAR(255) NOT NULL, tx_matricula_siape VARCHAR(255) NOT NULL, tx_observacao VARCHAR(255) DEFAULT NULL, criado_em DATETIME DEFAULT NULL, atualizado_em DATETIME DEFAULT NULL, apagado_em DATETIME DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', UNIQUE INDEX UNIQ_7001BA03D17F50A6 (uuid), INDEX IDX_7001BA03AAA822D2 (processo_id), INDEX IDX_7001BA03DB38439E (usuario_id), INDEX IDX_7001BA03F69C7D9B (criado_por), INDEX IDX_7001BA03AF2B1A92 (atualizado_por), INDEX IDX_7001BA03A395BB94 (apagado_por), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dc_mod_iniciativa (id INT AUTO_INCREMENT NOT NULL, criado_por INT DEFAULT NULL, atualizado_por INT DEFAULT NULL, apagado_por INT DEFAULT NULL, valor VARCHAR(255) DEFAULT NULL, descricao VARCHAR(255) DEFAULT NULL, criado_em DATETIME DEFAULT NULL, atualizado_em DATETIME DEFAULT NULL, apagado_em DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', UNIQUE INDEX UNIQ_76A7C1FB2E892728 (valor), UNIQUE INDEX UNIQ_76A7C1FBD17F50A6 (uuid), INDEX IDX_76A7C1FBF69C7D9B (criado_por), INDEX IDX_76A7C1FBAF2B1A92 (atualizado_por), INDEX IDX_76A7C1FBA395BB94 (apagado_por), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dc_mod_situacao (id INT AUTO_INCREMENT NOT NULL, criado_por INT DEFAULT NULL, atualizado_por INT DEFAULT NULL, apagado_por INT DEFAULT NULL, valor VARCHAR(255) DEFAULT NULL, descricao VARCHAR(255) DEFAULT NULL, criado_em DATETIME DEFAULT NULL, atualizado_em DATETIME DEFAULT NULL, apagado_em DATETIME DEFAULT NULL, ativo TINYINT(1) NOT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', UNIQUE INDEX UNIQ_347132792E892728 (valor), UNIQUE INDEX UNIQ_34713279D17F50A6 (uuid), INDEX IDX_34713279F69C7D9B (criado_por), INDEX IDX_34713279AF2B1A92 (atualizado_por), INDEX IDX_34713279A395BB94 (apagado_por), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dc_motivo (id INT AUTO_INCREMENT NOT NULL, criado_por INT DEFAULT NULL, atualizado_por INT DEFAULT NULL, apagado_por INT DEFAULT NULL, in_tipo VARCHAR(255) NOT NULL, nm_motivo VARCHAR(255) NOT NULL, num_dias_prazo INT DEFAULT NULL, criado_em DATETIME DEFAULT NULL, atualizado_em DATETIME DEFAULT NULL, apagado_em DATETIME DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', UNIQUE INDEX UNIQ_C44463C5D17F50A6 (uuid), INDEX IDX_C44463C5F69C7D9B (criado_por), INDEX IDX_C44463C5AF2B1A92 (atualizado_por), INDEX IDX_C44463C5A395BB94 (apagado_por), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dc_motivo_causa (id INT AUTO_INCREMENT NOT NULL, motivo_id INT NOT NULL, processo_id INT NOT NULL, criado_por INT DEFAULT NULL, atualizado_por INT DEFAULT NULL, apagado_por INT DEFAULT NULL, in_causa VARCHAR(255) NOT NULL, dt_inicio DATETIME NOT NULL, dt_fim DATE DEFAULT NULL, criado_em DATETIME DEFAULT NULL, atualizado_em DATETIME DEFAULT NULL, apagado_em DATETIME DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', UNIQUE INDEX UNIQ_60E82456D17F50A6 (uuid), INDEX IDX_60E82456F9E584F8 (motivo_id), INDEX IDX_60E82456AAA822D2 (processo_id), INDEX IDX_60E82456F69C7D9B (criado_por), INDEX IDX_60E82456AF2B1A92 (atualizado_por), INDEX IDX_60E82456A395BB94 (apagado_por), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dc_origem_representacao (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, criado_por INT DEFAULT NULL, atualizado_por INT DEFAULT NULL, apagado_por INT DEFAULT NULL, nm_orgao VARCHAR(255) DEFAULT NULL, lft INT NOT NULL, lvl INT NOT NULL, rgt INT NOT NULL, root INT DEFAULT NULL, criado_em DATETIME DEFAULT NULL, atualizado_em DATETIME DEFAULT NULL, apagado_em DATETIME DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', UNIQUE INDEX UNIQ_BFAD9750D17F50A6 (uuid), INDEX IDX_BFAD9750727ACA70 (parent_id), INDEX IDX_BFAD9750F69C7D9B (criado_por), INDEX IDX_BFAD9750AF2B1A92 (atualizado_por), INDEX IDX_BFAD9750A395BB94 (apagado_por), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dc_processo_juizo_admiss (id INT AUTO_INCREMENT NOT NULL, processo_id INT NOT NULL, mod_situacao_id INT DEFAULT NULL, origem_representacao_id INT NOT NULL, mod_iniciativa_id INT NOT NULL, cd_classe INT NOT NULL, criado_por INT DEFAULT NULL, atualizado_por INT DEFAULT NULL, apagado_por INT DEFAULT NULL, in_juizo_admissibilidade TINYINT(1) DEFAULT NULL, dt_recebimento_orgao DATETIME NOT NULL, dt_cadastro DATETIME DEFAULT NULL, dt_conhecimento_admin DATETIME DEFAULT NULL, dt_conhecimento_autorid DATETIME DEFAULT NULL, dt_conclusao DATETIME DEFAULT NULL, criado_em DATETIME DEFAULT NULL, atualizado_em DATETIME DEFAULT NULL, apagado_em DATETIME DEFAULT NULL, dt_est_advertencia DATETIME DEFAULT NULL, dt_est_suspensao DATETIME DEFAULT NULL, dt_est_demissao DATETIME DEFAULT NULL, num_tempo_transcorrido INT DEFAULT NULL, dt_ultima_suspensao DATETIME DEFAULT NULL, num_dias_suspensos INT DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', UNIQUE INDEX UNIQ_73BB79A5D17F50A6 (uuid), INDEX IDX_73BB79A5AAA822D2 (processo_id), INDEX IDX_73BB79A5CD74F328 (mod_situacao_id), INDEX IDX_73BB79A5A4011EBA (origem_representacao_id), INDEX IDX_73BB79A548DB6CC2 (mod_iniciativa_id), INDEX IDX_73BB79A53C9E80E5 (cd_classe), INDEX IDX_73BB79A5F69C7D9B (criado_por), INDEX IDX_73BB79A5AF2B1A92 (atualizado_por), INDEX IDX_73BB79A5A395BB94 (apagado_por), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dc_processo_juizo_admiss_res (id INT AUTO_INCREMENT NOT NULL, processo_id INT NOT NULL, resultado_juizo_id INT NOT NULL, pessoa_id INT DEFAULT NULL, setor_id INT DEFAULT NULL, criado_por INT DEFAULT NULL, atualizado_por INT DEFAULT NULL, apagado_por INT DEFAULT NULL, dt_resultado DATETIME NOT NULL, criado_em DATETIME DEFAULT NULL, atualizado_em DATETIME DEFAULT NULL, apagado_em DATETIME DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', UNIQUE INDEX UNIQ_DB712EAFD17F50A6 (uuid), INDEX IDX_DB712EAFAAA822D2 (processo_id), INDEX IDX_DB712EAF74A6EA2D (resultado_juizo_id), INDEX IDX_DB712EAFDF6FA0A5 (pessoa_id), INDEX IDX_DB712EAF4D94F126 (setor_id), INDEX IDX_DB712EAFF69C7D9B (criado_por), INDEX IDX_DB712EAFAF2B1A92 (atualizado_por), INDEX IDX_DB712EAFA395BB94 (apagado_por), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dc_processo_pad (id INT AUTO_INCREMENT NOT NULL, processo_id INT NOT NULL, processo_juizo_admiss_id INT DEFAULT NULL, mod_situacao_id INT DEFAULT NULL, cd_classe INT NOT NULL, municipios_id INT NOT NULL, origem_representacao_id INT DEFAULT NULL, criado_por INT DEFAULT NULL, atualizado_por INT DEFAULT NULL, apagado_por INT DEFAULT NULL, dt_conhecimento_admin DATETIME DEFAULT NULL, dt_conhecimento_autoridade DATETIME NOT NULL, dt_alteracao DATETIME DEFAULT NULL, criado_em DATETIME DEFAULT NULL, atualizado_em DATETIME DEFAULT NULL, apagado_em DATETIME DEFAULT NULL, dt_est_advertencia DATETIME DEFAULT NULL, dt_est_suspensao DATETIME DEFAULT NULL, dt_est_demissao DATETIME DEFAULT NULL, num_tempo_transcorrido INT DEFAULT NULL, dt_ultima_suspensao DATETIME DEFAULT NULL, num_dias_suspensos INT DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', UNIQUE INDEX UNIQ_24289012D17F50A6 (uuid), INDEX IDX_24289012AAA822D2 (processo_id), INDEX IDX_24289012653515F8 (processo_juizo_admiss_id), INDEX IDX_24289012CD74F328 (mod_situacao_id), INDEX IDX_242890123C9E80E5 (cd_classe), INDEX IDX_242890124723E346 (municipios_id), INDEX IDX_24289012A4011EBA (origem_representacao_id), INDEX IDX_24289012F69C7D9B (criado_por), INDEX IDX_24289012AF2B1A92 (atualizado_por), INDEX IDX_24289012A395BB94 (apagado_por), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dc_resultado_juizo (id INT AUTO_INCREMENT NOT NULL, criado_por INT DEFAULT NULL, atualizado_por INT DEFAULT NULL, apagado_por INT DEFAULT NULL, nm_resultado VARCHAR(255) NOT NULL, criado_em DATETIME DEFAULT NULL, atualizado_em DATETIME DEFAULT NULL, apagado_em DATETIME DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', UNIQUE INDEX UNIQ_A8CA1D5D17F50A6 (uuid), INDEX IDX_A8CA1D5F69C7D9B (criado_por), INDEX IDX_A8CA1D5AF2B1A92 (atualizado_por), INDEX IDX_A8CA1D5A395BB94 (apagado_por), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dc_setor_responsavel (id INT AUTO_INCREMENT NOT NULL, setor_id INT NOT NULL, processo_id INT NOT NULL, criado_por INT DEFAULT NULL, atualizado_por INT DEFAULT NULL, apagado_por INT DEFAULT NULL, dt_designacao DATETIME NOT NULL, criado_em DATETIME DEFAULT NULL, atualizado_em DATETIME DEFAULT NULL, apagado_em DATETIME DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', UNIQUE INDEX UNIQ_F84BED22D17F50A6 (uuid), INDEX IDX_F84BED224D94F126 (setor_id), INDEX IDX_F84BED22AAA822D2 (processo_id), INDEX IDX_F84BED22F69C7D9B (criado_por), INDEX IDX_F84BED22AF2B1A92 (atualizado_por), INDEX IDX_F84BED22A395BB94 (apagado_por), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
            $this->addSql('CREATE TABLE dc_unidade_relacionada (id INT AUTO_INCREMENT NOT NULL, setor_id INT NOT NULL, processo_id INT NOT NULL, criado_por INT DEFAULT NULL, atualizado_por INT DEFAULT NULL, apagado_por INT DEFAULT NULL, criado_em DATETIME DEFAULT NULL, atualizado_em DATETIME DEFAULT NULL, apagado_em DATETIME DEFAULT NULL, uuid CHAR(36) NOT NULL COMMENT \'(DC2Type:guid)\', UNIQUE INDEX UNIQ_6350141CD17F50A6 (uuid), INDEX IDX_6350141C4D94F126 (setor_id), INDEX IDX_6350141CAAA822D2 (processo_id), INDEX IDX_6350141CF69C7D9B (criado_por), INDEX IDX_6350141CAF2B1A92 (atualizado_por), INDEX IDX_6350141CA395BB94 (apagado_por), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');


            $this->addSql('ALTER TABLE dc_classe ADD CONSTRAINT FK_523AE435727ACA70 FOREIGN KEY (parent_id) REFERENCES dc_classe (id) ON DELETE SET NULL');
            $this->addSql('ALTER TABLE dc_classe ADD CONSTRAINT FK_523AE435F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_classe ADD CONSTRAINT FK_523AE435AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_classe ADD CONSTRAINT FK_523AE435A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_especie_fase_disciplinar ADD CONSTRAINT FK_ADEAE831F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_especie_fase_disciplinar ADD CONSTRAINT FK_ADEAE831AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_especie_fase_disciplinar ADD CONSTRAINT FK_ADEAE831A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_fase ADD CONSTRAINT FK_B824244C8010FB26 FOREIGN KEY (especies_fases_disciplinar_id) REFERENCES dc_especie_fase_disciplinar (id)');
            $this->addSql('ALTER TABLE dc_fase ADD CONSTRAINT FK_B824244CAAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_fase ADD CONSTRAINT FK_B824244CF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_fase ADD CONSTRAINT FK_B824244CAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_fase ADD CONSTRAINT FK_B824244CA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_impedimento ADD CONSTRAINT FK_377BE4D7DB38439E FOREIGN KEY (usuario_id) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_impedimento ADD CONSTRAINT FK_377BE4D7AAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_impedimento ADD CONSTRAINT FK_377BE4D7F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_impedimento ADD CONSTRAINT FK_377BE4D7AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_impedimento ADD CONSTRAINT FK_377BE4D7A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_membro_comissao ADD CONSTRAINT FK_7001BA03AAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_membro_comissao ADD CONSTRAINT FK_7001BA03DB38439E FOREIGN KEY (usuario_id) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_membro_comissao ADD CONSTRAINT FK_7001BA03F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_membro_comissao ADD CONSTRAINT FK_7001BA03AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_membro_comissao ADD CONSTRAINT FK_7001BA03A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_mod_iniciativa ADD CONSTRAINT FK_76A7C1FBF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_mod_iniciativa ADD CONSTRAINT FK_76A7C1FBAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_mod_iniciativa ADD CONSTRAINT FK_76A7C1FBA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_mod_situacao ADD CONSTRAINT FK_34713279F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_mod_situacao ADD CONSTRAINT FK_34713279AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_mod_situacao ADD CONSTRAINT FK_34713279A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_motivo ADD CONSTRAINT FK_C44463C5F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_motivo ADD CONSTRAINT FK_C44463C5AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_motivo ADD CONSTRAINT FK_C44463C5A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_motivo_causa ADD CONSTRAINT FK_60E82456F9E584F8 FOREIGN KEY (motivo_id) REFERENCES dc_motivo (id)');
            $this->addSql('ALTER TABLE dc_motivo_causa ADD CONSTRAINT FK_60E82456AAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_motivo_causa ADD CONSTRAINT FK_60E82456F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_motivo_causa ADD CONSTRAINT FK_60E82456AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_motivo_causa ADD CONSTRAINT FK_60E82456A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_origem_representacao ADD CONSTRAINT FK_BFAD9750727ACA70 FOREIGN KEY (parent_id) REFERENCES dc_origem_representacao (id) ON DELETE SET NULL');
            $this->addSql('ALTER TABLE dc_origem_representacao ADD CONSTRAINT FK_BFAD9750F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_origem_representacao ADD CONSTRAINT FK_BFAD9750AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_origem_representacao ADD CONSTRAINT FK_BFAD9750A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss ADD CONSTRAINT FK_73BB79A5AAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss ADD CONSTRAINT FK_73BB79A5CD74F328 FOREIGN KEY (mod_situacao_id) REFERENCES dc_mod_situacao (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss ADD CONSTRAINT FK_73BB79A5A4011EBA FOREIGN KEY (origem_representacao_id) REFERENCES dc_origem_representacao (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss ADD CONSTRAINT FK_73BB79A548DB6CC2 FOREIGN KEY (mod_iniciativa_id) REFERENCES dc_mod_iniciativa (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss ADD CONSTRAINT FK_73BB79A53C9E80E5 FOREIGN KEY (cd_classe) REFERENCES dc_classe (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss ADD CONSTRAINT FK_73BB79A5F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss ADD CONSTRAINT FK_73BB79A5AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss ADD CONSTRAINT FK_73BB79A5A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res ADD CONSTRAINT FK_DB712EAFAAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res ADD CONSTRAINT FK_DB712EAF74A6EA2D FOREIGN KEY (resultado_juizo_id) REFERENCES dc_resultado_juizo (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res ADD CONSTRAINT FK_DB712EAFDF6FA0A5 FOREIGN KEY (pessoa_id) REFERENCES ad_pessoa (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res ADD CONSTRAINT FK_DB712EAF4D94F126 FOREIGN KEY (setor_id) REFERENCES ad_setor (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res ADD CONSTRAINT FK_DB712EAFF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res ADD CONSTRAINT FK_DB712EAFAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res ADD CONSTRAINT FK_DB712EAFA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_24289012AAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_24289012653515F8 FOREIGN KEY (processo_juizo_admiss_id) REFERENCES dc_processo_juizo_admiss (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_24289012CD74F328 FOREIGN KEY (mod_situacao_id) REFERENCES dc_mod_situacao (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_242890123C9E80E5 FOREIGN KEY (cd_classe) REFERENCES dc_classe (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_242890124723E346 FOREIGN KEY (municipios_id) REFERENCES ad_municipio (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_24289012A4011EBA FOREIGN KEY (origem_representacao_id) REFERENCES dc_origem_representacao (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_24289012F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_24289012AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_processo_pad ADD CONSTRAINT FK_24289012A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_resultado_juizo ADD CONSTRAINT FK_A8CA1D5F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_resultado_juizo ADD CONSTRAINT FK_A8CA1D5AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_resultado_juizo ADD CONSTRAINT FK_A8CA1D5A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_setor_responsavel ADD CONSTRAINT FK_F84BED224D94F126 FOREIGN KEY (setor_id) REFERENCES ad_setor (id)');
            $this->addSql('ALTER TABLE dc_setor_responsavel ADD CONSTRAINT FK_F84BED22AAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_setor_responsavel ADD CONSTRAINT FK_F84BED22F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_setor_responsavel ADD CONSTRAINT FK_F84BED22AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_setor_responsavel ADD CONSTRAINT FK_F84BED22A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_unidade_relacionada ADD CONSTRAINT FK_6350141C4D94F126 FOREIGN KEY (setor_id) REFERENCES ad_setor (id)');
            $this->addSql('ALTER TABLE dc_unidade_relacionada ADD CONSTRAINT FK_6350141CAAA822D2 FOREIGN KEY (processo_id) REFERENCES ad_processo (id)');
            $this->addSql('ALTER TABLE dc_unidade_relacionada ADD CONSTRAINT FK_6350141CF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_unidade_relacionada ADD CONSTRAINT FK_6350141CAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE dc_unidade_relacionada ADD CONSTRAINT FK_6350141CA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
        }
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        if ('oracle' === $this->connection->getDatabasePlatform()->getName() ||
            'postgresql' === $this->connection->getDatabasePlatform()->getName()) {
            $this->addSql('DROP SEQUENCE dc_classe_id_seq');
            $this->addSql('DROP SEQUENCE dc_especie_fase_disciplinar_id');
            $this->addSql('DROP SEQUENCE dc_fase_id_seq');
            $this->addSql('DROP SEQUENCE dc_impedimento_id_seq');
            $this->addSql('DROP SEQUENCE dc_membro_comissao_id_seq');
            $this->addSql('DROP SEQUENCE dc_mod_iniciativa_id_seq');
            $this->addSql('DROP SEQUENCE dc_mod_situacao_id_seq');
            $this->addSql('DROP SEQUENCE dc_motivo_id_seq');
            $this->addSql('DROP SEQUENCE dc_motivo_causa_id_seq');
            $this->addSql('DROP SEQUENCE dc_origem_representacao_id_seq');
            $this->addSql('DROP SEQUENCE dc_processo_juizo_admiss_id_se');
            $this->addSql('DROP SEQUENCE dc_processo_juizo_admiss_res_i');
            $this->addSql('DROP SEQUENCE dc_processo_pad_id_seq');
            $this->addSql('DROP SEQUENCE dc_resultado_juizo_id_seq');
            $this->addSql('DROP SEQUENCE dc_setor_responsavel_id_seq');
            $this->addSql('DROP SEQUENCE dc_unidade_relacionada_id_seq');

            $this->addSql('ALTER TABLE dc_classe DROP CONSTRAINT FK_523AE435727ACA70');
            $this->addSql('ALTER TABLE dc_classe DROP CONSTRAINT FK_523AE435F69C7D9B');
            $this->addSql('ALTER TABLE dc_classe DROP CONSTRAINT FK_523AE435AF2B1A92');
            $this->addSql('ALTER TABLE dc_classe DROP CONSTRAINT FK_523AE435A395BB94');
            $this->addSql('ALTER TABLE dc_especie_fase_disciplinar DROP CONSTRAINT FK_ADEAE831F69C7D9B');
            $this->addSql('ALTER TABLE dc_especie_fase_disciplinar DROP CONSTRAINT FK_ADEAE831AF2B1A92');
            $this->addSql('ALTER TABLE dc_especie_fase_disciplinar DROP CONSTRAINT FK_ADEAE831A395BB94');
            $this->addSql('ALTER TABLE dc_fase DROP CONSTRAINT FK_B824244C8010FB26');
            $this->addSql('ALTER TABLE dc_fase DROP CONSTRAINT FK_B824244CAAA822D2');
            $this->addSql('ALTER TABLE dc_fase DROP CONSTRAINT FK_B824244CF69C7D9B');
            $this->addSql('ALTER TABLE dc_fase DROP CONSTRAINT FK_B824244CAF2B1A92');
            $this->addSql('ALTER TABLE dc_fase DROP CONSTRAINT FK_B824244CA395BB94');
            $this->addSql('ALTER TABLE dc_impedimento DROP CONSTRAINT FK_377BE4D7DB38439E');
            $this->addSql('ALTER TABLE dc_impedimento DROP CONSTRAINT FK_377BE4D7AAA822D2');
            $this->addSql('ALTER TABLE dc_impedimento DROP CONSTRAINT FK_377BE4D7F69C7D9B');
            $this->addSql('ALTER TABLE dc_impedimento DROP CONSTRAINT FK_377BE4D7AF2B1A92');
            $this->addSql('ALTER TABLE dc_impedimento DROP CONSTRAINT FK_377BE4D7A395BB94');
            $this->addSql('ALTER TABLE dc_membro_comissao DROP CONSTRAINT FK_7001BA03AAA822D2');
            $this->addSql('ALTER TABLE dc_membro_comissao DROP CONSTRAINT FK_7001BA03DB38439E');
            $this->addSql('ALTER TABLE dc_membro_comissao DROP CONSTRAINT FK_7001BA03F69C7D9B');
            $this->addSql('ALTER TABLE dc_membro_comissao DROP CONSTRAINT FK_7001BA03AF2B1A92');
            $this->addSql('ALTER TABLE dc_membro_comissao DROP CONSTRAINT FK_7001BA03A395BB94');
            $this->addSql('ALTER TABLE dc_mod_iniciativa DROP CONSTRAINT FK_76A7C1FBF69C7D9B');
            $this->addSql('ALTER TABLE dc_mod_iniciativa DROP CONSTRAINT FK_76A7C1FBAF2B1A92');
            $this->addSql('ALTER TABLE dc_mod_iniciativa DROP CONSTRAINT FK_76A7C1FBA395BB94');
            $this->addSql('ALTER TABLE dc_mod_situacao DROP CONSTRAINT FK_34713279F69C7D9B');
            $this->addSql('ALTER TABLE dc_mod_situacao DROP CONSTRAINT FK_34713279AF2B1A92');
            $this->addSql('ALTER TABLE dc_mod_situacao DROP CONSTRAINT FK_34713279A395BB94');
            $this->addSql('ALTER TABLE dc_motivo DROP CONSTRAINT FK_C44463C5F69C7D9B');
            $this->addSql('ALTER TABLE dc_motivo DROP CONSTRAINT FK_C44463C5AF2B1A92');
            $this->addSql('ALTER TABLE dc_motivo DROP CONSTRAINT FK_C44463C5A395BB94');
            $this->addSql('ALTER TABLE dc_motivo_causa DROP CONSTRAINT FK_60E82456F9E584F8');
            $this->addSql('ALTER TABLE dc_motivo_causa DROP CONSTRAINT FK_60E82456AAA822D2');
            $this->addSql('ALTER TABLE dc_motivo_causa DROP CONSTRAINT FK_60E82456F69C7D9B');
            $this->addSql('ALTER TABLE dc_motivo_causa DROP CONSTRAINT FK_60E82456AF2B1A92');
            $this->addSql('ALTER TABLE dc_motivo_causa DROP CONSTRAINT FK_60E82456A395BB94');
            $this->addSql('ALTER TABLE dc_origem_representacao DROP CONSTRAINT FK_BFAD9750727ACA70');
            $this->addSql('ALTER TABLE dc_origem_representacao DROP CONSTRAINT FK_BFAD9750F69C7D9B');
            $this->addSql('ALTER TABLE dc_origem_representacao DROP CONSTRAINT FK_BFAD9750AF2B1A92');
            $this->addSql('ALTER TABLE dc_origem_representacao DROP CONSTRAINT FK_BFAD9750A395BB94');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss DROP CONSTRAINT FK_73BB79A5AAA822D2');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss DROP CONSTRAINT FK_73BB79A5CD74F328');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss DROP CONSTRAINT FK_73BB79A5A4011EBA');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss DROP CONSTRAINT FK_73BB79A548DB6CC2');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss DROP CONSTRAINT FK_73BB79A53C9E80E5');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss DROP CONSTRAINT FK_73BB79A5F69C7D9B');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss DROP CONSTRAINT FK_73BB79A5AF2B1A92');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss DROP CONSTRAINT FK_73BB79A5A395BB94');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res DROP CONSTRAINT FK_DB712EAFAAA822D2');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res DROP CONSTRAINT FK_DB712EAF74A6EA2D');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res DROP CONSTRAINT FK_DB712EAFDF6FA0A5');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res DROP CONSTRAINT FK_DB712EAF4D94F126');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res DROP CONSTRAINT FK_DB712EAFF69C7D9B');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res DROP CONSTRAINT FK_DB712EAFAF2B1A92');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res DROP CONSTRAINT FK_DB712EAFA395BB94');
            $this->addSql('ALTER TABLE dc_processo_pad DROP CONSTRAINT FK_24289012AAA822D2');
            $this->addSql('ALTER TABLE dc_processo_pad DROP CONSTRAINT FK_24289012653515F8');
            $this->addSql('ALTER TABLE dc_processo_pad DROP CONSTRAINT FK_24289012CD74F328');
            $this->addSql('ALTER TABLE dc_processo_pad DROP CONSTRAINT FK_242890123C9E80E5');
            $this->addSql('ALTER TABLE dc_processo_pad DROP CONSTRAINT FK_242890124723E346');
            $this->addSql('ALTER TABLE dc_processo_pad DROP CONSTRAINT FK_24289012A4011EBA');
            $this->addSql('ALTER TABLE dc_processo_pad DROP CONSTRAINT FK_24289012F69C7D9B');
            $this->addSql('ALTER TABLE dc_processo_pad DROP CONSTRAINT FK_24289012AF2B1A92');
            $this->addSql('ALTER TABLE dc_processo_pad DROP CONSTRAINT FK_24289012A395BB94');
            $this->addSql('ALTER TABLE dc_resultado_juizo DROP CONSTRAINT FK_A8CA1D5F69C7D9B');
            $this->addSql('ALTER TABLE dc_resultado_juizo DROP CONSTRAINT FK_A8CA1D5AF2B1A92');
            $this->addSql('ALTER TABLE dc_resultado_juizo DROP CONSTRAINT FK_A8CA1D5A395BB94');
            $this->addSql('ALTER TABLE dc_setor_responsavel DROP CONSTRAINT FK_F84BED224D94F126');
            $this->addSql('ALTER TABLE dc_setor_responsavel DROP CONSTRAINT FK_F84BED22AAA822D2');
            $this->addSql('ALTER TABLE dc_setor_responsavel DROP CONSTRAINT FK_F84BED22F69C7D9B');
            $this->addSql('ALTER TABLE dc_setor_responsavel DROP CONSTRAINT FK_F84BED22AF2B1A92');
            $this->addSql('ALTER TABLE dc_setor_responsavel DROP CONSTRAINT FK_F84BED22A395BB94');
            $this->addSql('ALTER TABLE dc_unidade_relacionada DROP CONSTRAINT FK_6350141C4D94F126');
            $this->addSql('ALTER TABLE dc_unidade_relacionada DROP CONSTRAINT FK_6350141CAAA822D2');
            $this->addSql('ALTER TABLE dc_unidade_relacionada DROP CONSTRAINT FK_6350141CF69C7D9B');
            $this->addSql('ALTER TABLE dc_unidade_relacionada DROP CONSTRAINT FK_6350141CAF2B1A92');
            $this->addSql('ALTER TABLE dc_unidade_relacionada DROP CONSTRAINT FK_6350141CA395BB94');

            $this->addSql('DROP TABLE dc_classe');
            $this->addSql('DROP TABLE dc_especie_fase_disciplinar');
            $this->addSql('DROP TABLE dc_fase');
            $this->addSql('DROP TABLE dc_impedimento');
            $this->addSql('DROP TABLE dc_membro_comissao');
            $this->addSql('DROP TABLE dc_mod_iniciativa');
            $this->addSql('DROP TABLE dc_mod_situacao');
            $this->addSql('DROP TABLE dc_motivo');
            $this->addSql('DROP TABLE dc_motivo_causa');
            $this->addSql('DROP TABLE dc_origem_representacao');
            $this->addSql('DROP TABLE dc_processo_juizo_admiss');
            $this->addSql('DROP TABLE dc_processo_juizo_admiss_res');
            $this->addSql('DROP TABLE dc_processo_pad');
            $this->addSql('DROP TABLE dc_resultado_juizo');
            $this->addSql('DROP TABLE dc_setor_responsavel');
            $this->addSql('DROP TABLE dc_unidade_relacionada');

        } else {
            $this->addSql('ALTER TABLE dc_classe DROP FOREIGN KEY FK_523AE435727ACA70');
            $this->addSql('ALTER TABLE dc_classe DROP FOREIGN KEY FK_523AE435F69C7D9B');
            $this->addSql('ALTER TABLE dc_classe DROP FOREIGN KEY FK_523AE435AF2B1A92');
            $this->addSql('ALTER TABLE dc_classe DROP FOREIGN KEY FK_523AE435A395BB94');
            $this->addSql('ALTER TABLE dc_especie_fase_disciplinar DROP FOREIGN KEY FK_ADEAE831F69C7D9B');
            $this->addSql('ALTER TABLE dc_especie_fase_disciplinar DROP FOREIGN KEY FK_ADEAE831AF2B1A92');
            $this->addSql('ALTER TABLE dc_especie_fase_disciplinar DROP FOREIGN KEY FK_ADEAE831A395BB94');
            $this->addSql('ALTER TABLE dc_fase DROP FOREIGN KEY FK_B824244C8010FB26');
            $this->addSql('ALTER TABLE dc_fase DROP FOREIGN KEY FK_B824244CAAA822D2');
            $this->addSql('ALTER TABLE dc_fase DROP FOREIGN KEY FK_B824244CF69C7D9B');
            $this->addSql('ALTER TABLE dc_fase DROP FOREIGN KEY FK_B824244CAF2B1A92');
            $this->addSql('ALTER TABLE dc_fase DROP FOREIGN KEY FK_B824244CA395BB94');
            $this->addSql('ALTER TABLE dc_impedimento DROP FOREIGN KEY FK_377BE4D7DB38439E');
            $this->addSql('ALTER TABLE dc_impedimento DROP FOREIGN KEY FK_377BE4D7AAA822D2');
            $this->addSql('ALTER TABLE dc_impedimento DROP FOREIGN KEY FK_377BE4D7F69C7D9B');
            $this->addSql('ALTER TABLE dc_impedimento DROP FOREIGN KEY FK_377BE4D7AF2B1A92');
            $this->addSql('ALTER TABLE dc_impedimento DROP FOREIGN KEY FK_377BE4D7A395BB94');
            $this->addSql('ALTER TABLE dc_membro_comissao DROP FOREIGN KEY FK_7001BA03AAA822D2');
            $this->addSql('ALTER TABLE dc_membro_comissao DROP FOREIGN KEY FK_7001BA03DB38439E');
            $this->addSql('ALTER TABLE dc_membro_comissao DROP FOREIGN KEY FK_7001BA03F69C7D9B');
            $this->addSql('ALTER TABLE dc_membro_comissao DROP FOREIGN KEY FK_7001BA03AF2B1A92');
            $this->addSql('ALTER TABLE dc_membro_comissao DROP FOREIGN KEY FK_7001BA03A395BB94');
            $this->addSql('ALTER TABLE dc_mod_iniciativa DROP FOREIGN KEY FK_76A7C1FBF69C7D9B');
            $this->addSql('ALTER TABLE dc_mod_iniciativa DROP FOREIGN KEY FK_76A7C1FBAF2B1A92');
            $this->addSql('ALTER TABLE dc_mod_iniciativa DROP FOREIGN KEY FK_76A7C1FBA395BB94');
            $this->addSql('ALTER TABLE dc_mod_situacao DROP FOREIGN KEY FK_34713279F69C7D9B');
            $this->addSql('ALTER TABLE dc_mod_situacao DROP FOREIGN KEY FK_34713279AF2B1A92');
            $this->addSql('ALTER TABLE dc_mod_situacao DROP FOREIGN KEY FK_34713279A395BB94');
            $this->addSql('ALTER TABLE dc_motivo DROP FOREIGN KEY FK_C44463C5F69C7D9B');
            $this->addSql('ALTER TABLE dc_motivo DROP FOREIGN KEY FK_C44463C5AF2B1A92');
            $this->addSql('ALTER TABLE dc_motivo DROP FOREIGN KEY FK_C44463C5A395BB94');
            $this->addSql('ALTER TABLE dc_motivo_causa DROP FOREIGN KEY FK_60E82456F9E584F8');
            $this->addSql('ALTER TABLE dc_motivo_causa DROP FOREIGN KEY FK_60E82456AAA822D2');
            $this->addSql('ALTER TABLE dc_motivo_causa DROP FOREIGN KEY FK_60E82456F69C7D9B');
            $this->addSql('ALTER TABLE dc_motivo_causa DROP FOREIGN KEY FK_60E82456AF2B1A92');
            $this->addSql('ALTER TABLE dc_motivo_causa DROP FOREIGN KEY FK_60E82456A395BB94');
            $this->addSql('ALTER TABLE dc_origem_representacao DROP FOREIGN KEY FK_BFAD9750727ACA70');
            $this->addSql('ALTER TABLE dc_origem_representacao DROP FOREIGN KEY FK_BFAD9750F69C7D9B');
            $this->addSql('ALTER TABLE dc_origem_representacao DROP FOREIGN KEY FK_BFAD9750AF2B1A92');
            $this->addSql('ALTER TABLE dc_origem_representacao DROP FOREIGN KEY FK_BFAD9750A395BB94');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss DROP FOREIGN KEY FK_73BB79A5AAA822D2');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss DROP FOREIGN KEY FK_73BB79A5CD74F328');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss DROP FOREIGN KEY FK_73BB79A5A4011EBA');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss DROP FOREIGN KEY FK_73BB79A548DB6CC2');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss DROP FOREIGN KEY FK_73BB79A53C9E80E5');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss DROP FOREIGN KEY FK_73BB79A5F69C7D9B');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss DROP FOREIGN KEY FK_73BB79A5AF2B1A92');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss DROP FOREIGN KEY FK_73BB79A5A395BB94');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res DROP FOREIGN KEY FK_DB712EAFAAA822D2');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res DROP FOREIGN KEY FK_DB712EAF74A6EA2D');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res DROP FOREIGN KEY FK_DB712EAFDF6FA0A5');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res DROP FOREIGN KEY FK_DB712EAF4D94F126');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res DROP FOREIGN KEY FK_DB712EAFF69C7D9B');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res DROP FOREIGN KEY FK_DB712EAFAF2B1A92');
            $this->addSql('ALTER TABLE dc_processo_juizo_admiss_res DROP FOREIGN KEY FK_DB712EAFA395BB94');
            $this->addSql('ALTER TABLE dc_processo_pad DROP FOREIGN KEY FK_24289012AAA822D2');
            $this->addSql('ALTER TABLE dc_processo_pad DROP FOREIGN KEY FK_24289012653515F8');
            $this->addSql('ALTER TABLE dc_processo_pad DROP FOREIGN KEY FK_24289012CD74F328');
            $this->addSql('ALTER TABLE dc_processo_pad DROP FOREIGN KEY FK_242890123C9E80E5');
            $this->addSql('ALTER TABLE dc_processo_pad DROP FOREIGN KEY FK_242890124723E346');
            $this->addSql('ALTER TABLE dc_processo_pad DROP FOREIGN KEY FK_24289012A4011EBA');
            $this->addSql('ALTER TABLE dc_processo_pad DROP FOREIGN KEY FK_24289012F69C7D9B');
            $this->addSql('ALTER TABLE dc_processo_pad DROP FOREIGN KEY FK_24289012AF2B1A92');
            $this->addSql('ALTER TABLE dc_processo_pad DROP FOREIGN KEY FK_24289012A395BB94');
            $this->addSql('ALTER TABLE dc_resultado_juizo DROP FOREIGN KEY FK_A8CA1D5F69C7D9B');
            $this->addSql('ALTER TABLE dc_resultado_juizo DROP FOREIGN KEY FK_A8CA1D5AF2B1A92');
            $this->addSql('ALTER TABLE dc_resultado_juizo DROP FOREIGN KEY FK_A8CA1D5A395BB94');
            $this->addSql('ALTER TABLE dc_setor_responsavel DROP FOREIGN KEY FK_F84BED224D94F126');
            $this->addSql('ALTER TABLE dc_setor_responsavel DROP FOREIGN KEY FK_F84BED22AAA822D2');
            $this->addSql('ALTER TABLE dc_setor_responsavel DROP FOREIGN KEY FK_F84BED22F69C7D9B');
            $this->addSql('ALTER TABLE dc_setor_responsavel DROP FOREIGN KEY FK_F84BED22AF2B1A92');
            $this->addSql('ALTER TABLE dc_setor_responsavel DROP FOREIGN KEY FK_F84BED22A395BB94');
            $this->addSql('ALTER TABLE dc_unidade_relacionada DROP FOREIGN KEY FK_6350141C4D94F126');
            $this->addSql('ALTER TABLE dc_unidade_relacionada DROP FOREIGN KEY FK_6350141CAAA822D2');
            $this->addSql('ALTER TABLE dc_unidade_relacionada DROP FOREIGN KEY FK_6350141CF69C7D9B');
            $this->addSql('ALTER TABLE dc_unidade_relacionada DROP FOREIGN KEY FK_6350141CAF2B1A92');
            $this->addSql('ALTER TABLE dc_unidade_relacionada DROP FOREIGN KEY FK_6350141CA395BB94');

            $this->addSql('DROP TABLE dc_classe');
            $this->addSql('DROP TABLE dc_especie_fase_disciplinar');
            $this->addSql('DROP TABLE dc_fase');
            $this->addSql('DROP TABLE dc_impedimento');
            $this->addSql('DROP TABLE dc_membro_comissao');
            $this->addSql('DROP TABLE dc_mod_iniciativa');
            $this->addSql('DROP TABLE dc_mod_situacao');
            $this->addSql('DROP TABLE dc_motivo');
            $this->addSql('DROP TABLE dc_motivo_causa');
            $this->addSql('DROP TABLE dc_origem_representacao');
            $this->addSql('DROP TABLE dc_processo_juizo_admiss');
            $this->addSql('DROP TABLE dc_processo_juizo_admiss_res');
            $this->addSql('DROP TABLE dc_processo_pad');
            $this->addSql('DROP TABLE dc_resultado_juizo');
            $this->addSql('DROP TABLE dc_setor_responsavel');
            $this->addSql('DROP TABLE dc_unidade_relacionada');
        }
    }
}
