<?php

declare(strict_types=1);

namespace SuppCore\AdministrativoBackend\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240223223521ECarta extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'migration from 1.14.0 to 1.15.0';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        if ('oracle' === $this->connection->getDatabasePlatform()->getName() ||
            'postgresql' === $this->connection->getDatabasePlatform()->getName()) {
            $this->addSql('CREATE SEQUENCE tb_arquivo_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE tb_baixa_rastreamento_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE tb_cancelamento_lote_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE tb_devolucao_ar_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE tb_inconsistencia_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE tb_lote_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE tb_lote_devolucao_ar_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE tb_recibo_servico_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE tb_recusa_resposta_ar_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE tb_resp_cancelamento_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE tb_resposta_ar_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE tb_resposta_notificacao_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE tb_servico_referencia_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE tb_tipo_inconsistencia_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
            $this->addSql('CREATE SEQUENCE tb_tipo_resposta_ar_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');

            $this->addSql('CREATE TABLE tb_arquivo (id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, nm_arq VARCHAR2(255) NOT NULL, nr_linhas NUMBER(10) DEFAULT NULL NULL, nr_ult_linha_proc NUMBER(10) DEFAULT NULL NULL, in_gerado NUMBER(1) NOT NULL, dt_inicio_proc TIMESTAMP(0) DEFAULT NULL NULL, dt_fim_proc TIMESTAMP(0) DEFAULT NULL NULL, dt_inicio_geracao TIMESTAMP(0) DEFAULT NULL NULL, dt_fim_geracao TIMESTAMP(0) DEFAULT NULL NULL, tx_hash VARCHAR2(100) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_F2AD2580F69C7D9B ON tb_arquivo (criado_por)');
            $this->addSql('CREATE INDEX IDX_F2AD2580AF2B1A92 ON tb_arquivo (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_F2AD2580A395BB94 ON tb_arquivo (apagado_por)');
            $this->addSql('COMMENT ON COLUMN tb_arquivo.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE tb_baixa_rastreamento (id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, ds_baixa_rastreamento VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_23B01B22F69C7D9B ON tb_baixa_rastreamento (criado_por)');
            $this->addSql('CREATE INDEX IDX_23B01B22AF2B1A92 ON tb_baixa_rastreamento (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_23B01B22A395BB94 ON tb_baixa_rastreamento (apagado_por)');
            $this->addSql('COMMENT ON COLUMN tb_baixa_rastreamento.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE tb_cancelamento_lote (id NUMBER(10) NOT NULL, lote_id NUMBER(10) NOT NULL, arquivo_id NUMBER(10) DEFAULT NULL NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, cd_matriz_objeto_cliente NUMBER(10) NOT NULL, in_confirmado NUMBER(1) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_5C50DC79B172197C ON tb_cancelamento_lote (lote_id)');
            $this->addSql('CREATE INDEX IDX_5C50DC797E7C3263 ON tb_cancelamento_lote (arquivo_id)');
            $this->addSql('CREATE INDEX IDX_5C50DC79F69C7D9B ON tb_cancelamento_lote (criado_por)');
            $this->addSql('CREATE INDEX IDX_5C50DC79AF2B1A92 ON tb_cancelamento_lote (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_5C50DC79A395BB94 ON tb_cancelamento_lote (apagado_por)');
            $this->addSql('COMMENT ON COLUMN tb_cancelamento_lote.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE tb_devolucao_ar (id NUMBER(10) NOT NULL, lote_id NUMBER(10) DEFAULT NULL NULL, documentos_id NUMBER(10) DEFAULT NULL NULL, baixa_rastreamento_id NUMBER(10) NOT NULL, arquivo_id NUMBER(10) DEFAULT NULL NULL, lote_devolucao_id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, cd_objeto_cliente VARCHAR2(255) NOT NULL, cd_lote VARCHAR2(10) NOT NULL, nr_etiqueta VARCHAR2(255) NOT NULL, nr_etiqueta_ar VARCHAR2(255) DEFAULT NULL NULL, nm_arquivo VARCHAR2(255) DEFAULT NULL NULL, nr_linha NUMBER(10) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_BF8E6E10B172197C ON tb_devolucao_ar (lote_id)');
            $this->addSql('CREATE INDEX IDX_BF8E6E10C75BF859 ON tb_devolucao_ar (documentos_id)');
            $this->addSql('CREATE INDEX IDX_BF8E6E1046E7720A ON tb_devolucao_ar (baixa_rastreamento_id)');
            $this->addSql('CREATE INDEX IDX_BF8E6E107E7C3263 ON tb_devolucao_ar (arquivo_id)');
            $this->addSql('CREATE INDEX IDX_BF8E6E10A924DC31 ON tb_devolucao_ar (lote_devolucao_id)');
            $this->addSql('CREATE INDEX IDX_BF8E6E10F69C7D9B ON tb_devolucao_ar (criado_por)');
            $this->addSql('CREATE INDEX IDX_BF8E6E10AF2B1A92 ON tb_devolucao_ar (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_BF8E6E10A395BB94 ON tb_devolucao_ar (apagado_por)');
            $this->addSql('COMMENT ON COLUMN tb_devolucao_ar.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE tb_inconsistencia (id NUMBER(10) NOT NULL, tipo_inconsistencia_id NUMBER(10) DEFAULT NULL NULL, arquivo_id NUMBER(10) DEFAULT NULL NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, ds_inconsistencia VARCHAR2(255) NOT NULL, nr_linha NUMBER(10) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_3A7A94BDBE86A4FA ON tb_inconsistencia (tipo_inconsistencia_id)');
            $this->addSql('CREATE INDEX IDX_3A7A94BD7E7C3263 ON tb_inconsistencia (arquivo_id)');
            $this->addSql('CREATE INDEX IDX_3A7A94BDF69C7D9B ON tb_inconsistencia (criado_por)');
            $this->addSql('CREATE INDEX IDX_3A7A94BDAF2B1A92 ON tb_inconsistencia (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_3A7A94BDA395BB94 ON tb_inconsistencia (apagado_por)');
            $this->addSql('COMMENT ON COLUMN tb_inconsistencia.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE tb_lote (id NUMBER(10) NOT NULL, inconsistencia_id NUMBER(10) DEFAULT NULL NULL, arquivo_id NUMBER(10) DEFAULT NULL NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, dt_envio TIMESTAMP(0) DEFAULT NULL NULL, dt_retorno TIMESTAMP(0) DEFAULT NULL NULL, cd_matriz_objeto_cliente NUMBER(10) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_3EC4308E3446B1F9 ON tb_lote (inconsistencia_id)');
            $this->addSql('CREATE INDEX IDX_3EC4308E7E7C3263 ON tb_lote (arquivo_id)');
            $this->addSql('CREATE INDEX IDX_3EC4308EF69C7D9B ON tb_lote (criado_por)');
            $this->addSql('CREATE INDEX IDX_3EC4308EAF2B1A92 ON tb_lote (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_3EC4308EA395BB94 ON tb_lote (apagado_por)');
            $this->addSql('COMMENT ON COLUMN tb_lote.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE tb_lote_devolucao_ar (id NUMBER(10) NOT NULL, arquivo_id NUMBER(10) DEFAULT NULL NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, cd_lote_devolucao NUMBER(10) NOT NULL, dt_lote TIMESTAMP(0) NOT NULL, cd_matriz_objeto_cliente NUMBER(10) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_AF552DE47E7C3263 ON tb_lote_devolucao_ar (arquivo_id)');
            $this->addSql('CREATE INDEX IDX_AF552DE4F69C7D9B ON tb_lote_devolucao_ar (criado_por)');
            $this->addSql('CREATE INDEX IDX_AF552DE4AF2B1A92 ON tb_lote_devolucao_ar (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_AF552DE4A395BB94 ON tb_lote_devolucao_ar (apagado_por)');
            $this->addSql('COMMENT ON COLUMN tb_lote_devolucao_ar.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE tb_recibo_servico (id NUMBER(10) NOT NULL, lote_id NUMBER(10) DEFAULT NULL NULL, arquivo_id NUMBER(10) DEFAULT NULL NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, cd_objeto_cliente VARCHAR2(255) NOT NULL, nr_etiqueta VARCHAR2(255) NOT NULL, ds_limite_postagem VARCHAR2(255) DEFAULT NULL NULL, nr_linha NUMBER(10) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_90C1484AB172197C ON tb_recibo_servico (lote_id)');
            $this->addSql('CREATE INDEX IDX_90C1484A7E7C3263 ON tb_recibo_servico (arquivo_id)');
            $this->addSql('CREATE INDEX IDX_90C1484AF69C7D9B ON tb_recibo_servico (criado_por)');
            $this->addSql('CREATE INDEX IDX_90C1484AAF2B1A92 ON tb_recibo_servico (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_90C1484AA395BB94 ON tb_recibo_servico (apagado_por)');
            $this->addSql('COMMENT ON COLUMN tb_recibo_servico.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE tb_recusa_resposta_ar (id NUMBER(10) NOT NULL, lote_devolucao_ar_id NUMBER(10) NOT NULL, arquivo_id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, nm_arquivo_recebido VARCHAR2(255) NOT NULL, tx_mensagem_erro VARCHAR2(255) NOT NULL, in_reenviado NUMBER(1) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_C87DC95C1764677E ON tb_recusa_resposta_ar (lote_devolucao_ar_id)');
            $this->addSql('CREATE INDEX IDX_C87DC95C7E7C3263 ON tb_recusa_resposta_ar (arquivo_id)');
            $this->addSql('CREATE INDEX IDX_C87DC95CF69C7D9B ON tb_recusa_resposta_ar (criado_por)');
            $this->addSql('CREATE INDEX IDX_C87DC95CAF2B1A92 ON tb_recusa_resposta_ar (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_C87DC95CA395BB94 ON tb_recusa_resposta_ar (apagado_por)');
            $this->addSql('COMMENT ON COLUMN tb_recusa_resposta_ar.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE tb_resp_cancelamento (id NUMBER(10) NOT NULL, lote_id NUMBER(10) NOT NULL, arquivo_id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, cd_matriz_objeto_cliente NUMBER(10) NOT NULL, in_confirmado NUMBER(1) NOT NULL, ds_mensagem VARCHAR2(255) NOT NULL, nr_linha NUMBER(10) DEFAULT NULL NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_1919680FB172197C ON tb_resp_cancelamento (lote_id)');
            $this->addSql('CREATE INDEX IDX_1919680F7E7C3263 ON tb_resp_cancelamento (arquivo_id)');
            $this->addSql('CREATE INDEX IDX_1919680FF69C7D9B ON tb_resp_cancelamento (criado_por)');
            $this->addSql('CREATE INDEX IDX_1919680FAF2B1A92 ON tb_resp_cancelamento (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_1919680FA395BB94 ON tb_resp_cancelamento (apagado_por)');
            $this->addSql('COMMENT ON COLUMN tb_resp_cancelamento.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE tb_resposta_ar (id NUMBER(10) NOT NULL, lote_id NUMBER(10) DEFAULT NULL NULL, tipo_resposta_ar_id NUMBER(10) DEFAULT NULL NULL, arquivo_id NUMBER(10) DEFAULT NULL NULL, lote_devolucao_id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, cd_objeto_cliente VARCHAR2(255) NOT NULL, cd_lote VARCHAR2(10) NOT NULL, ds_resposta_notificacao VARCHAR2(1) NOT NULL, nr_etiqueta VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_2C4B1306B172197C ON tb_resposta_ar (lote_id)');
            $this->addSql('CREATE INDEX IDX_2C4B13065E64109 ON tb_resposta_ar (tipo_resposta_ar_id)');
            $this->addSql('CREATE INDEX IDX_2C4B13067E7C3263 ON tb_resposta_ar (arquivo_id)');
            $this->addSql('CREATE INDEX IDX_2C4B1306A924DC31 ON tb_resposta_ar (lote_devolucao_id)');
            $this->addSql('CREATE INDEX IDX_2C4B1306F69C7D9B ON tb_resposta_ar (criado_por)');
            $this->addSql('CREATE INDEX IDX_2C4B1306AF2B1A92 ON tb_resposta_ar (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_2C4B1306A395BB94 ON tb_resposta_ar (apagado_por)');
            $this->addSql('COMMENT ON COLUMN tb_resposta_ar.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE tb_resposta_notificacao (id NUMBER(10) NOT NULL, lote_id NUMBER(10) DEFAULT NULL NULL, arquivo_id NUMBER(10) DEFAULT NULL NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, ds_resposta_notificacao VARCHAR2(1) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_3E98115B172197C ON tb_resposta_notificacao (lote_id)');
            $this->addSql('CREATE INDEX IDX_3E981157E7C3263 ON tb_resposta_notificacao (arquivo_id)');
            $this->addSql('CREATE INDEX IDX_3E98115F69C7D9B ON tb_resposta_notificacao (criado_por)');
            $this->addSql('CREATE INDEX IDX_3E98115AF2B1A92 ON tb_resposta_notificacao (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_3E98115A395BB94 ON tb_resposta_notificacao (apagado_por)');
            $this->addSql('CREATE INDEX IDX_3E98115FF6A170EBF396750 ON tb_resposta_notificacao (apagado_em, id)');
            $this->addSql('COMMENT ON COLUMN tb_resposta_notificacao.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE tb_servico_referencia (id NUMBER(10) NOT NULL, lote_id NUMBER(10) DEFAULT NULL NULL, recibo_servico_id NUMBER(10) DEFAULT NULL NULL, devolucao_ar_id NUMBER(10) DEFAULT NULL NULL, resposta_ar_id NUMBER(10) DEFAULT NULL NULL, inconsistencia_id NUMBER(10) DEFAULT NULL NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, cd_objeto_cliente VARCHAR2(255) NOT NULL, cd_cartao_postagem VARCHAR2(10) DEFAULT NULL NULL, cd_numero_contrato VARCHAR2(10) DEFAULT NULL NULL, cd_servico_adicional VARCHAR2(3) DEFAULT NULL NULL, cd_arquivo_spool VARCHAR2(255) DEFAULT NULL NULL, nm_arquivo_spool VARCHAR2(255) DEFAULT NULL NULL, cd_arquivo_complementar VARCHAR2(255) DEFAULT NULL NULL, nm_arquivo_complementar VARCHAR2(255) DEFAULT NULL NULL, nm_destinatario VARCHAR2(255) NOT NULL, tx_end_dest VARCHAR2(255) NOT NULL, nr_end_dest VARCHAR2(255) DEFAULT NULL NULL, tx_complemento_end_dest VARCHAR2(255) DEFAULT NULL NULL, tx_bairro_end_dest VARCHAR2(255) DEFAULT NULL NULL, nm_cidade_end_dest VARCHAR2(255) NOT NULL, nm_uf_end_dest VARCHAR2(2) NOT NULL, nr_cep_end_dest VARCHAR2(255) NOT NULL, nm_remetente VARCHAR2(255) NOT NULL, tx_end_remetente VARCHAR2(255) NOT NULL, nr_cep_end_remetente VARCHAR2(255) NOT NULL, tx_status NUMBER(10) DEFAULT NULL NULL, tx_link VARCHAR2(200) DEFAULT NULL NULL, cd_matriz_objeto_cliente NUMBER(10) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_584071C8B172197C ON tb_servico_referencia (lote_id)');
            $this->addSql('CREATE INDEX IDX_584071C8F5F33411 ON tb_servico_referencia (recibo_servico_id)');
            $this->addSql('CREATE INDEX IDX_584071C8187B6982 ON tb_servico_referencia (devolucao_ar_id)');
            $this->addSql('CREATE INDEX IDX_584071C889358EA9 ON tb_servico_referencia (resposta_ar_id)');
            $this->addSql('CREATE INDEX IDX_584071C83446B1F9 ON tb_servico_referencia (inconsistencia_id)');
            $this->addSql('CREATE INDEX IDX_584071C8F69C7D9B ON tb_servico_referencia (criado_por)');
            $this->addSql('CREATE INDEX IDX_584071C8AF2B1A92 ON tb_servico_referencia (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_584071C8A395BB94 ON tb_servico_referencia (apagado_por)');
            $this->addSql('COMMENT ON COLUMN tb_servico_referencia.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE tb_tipo_inconsistencia (id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, ds_inconsistencia VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_365BB71CF69C7D9B ON tb_tipo_inconsistencia (criado_por)');
            $this->addSql('CREATE INDEX IDX_365BB71CAF2B1A92 ON tb_tipo_inconsistencia (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_365BB71CA395BB94 ON tb_tipo_inconsistencia (apagado_por)');
            $this->addSql('CREATE INDEX IDX_365BB71CFF6A170EBF396750 ON tb_tipo_inconsistencia (apagado_em, id)');
            $this->addSql('COMMENT ON COLUMN tb_tipo_inconsistencia.uuid IS \'(DC2Type:guid)\'');
            $this->addSql('CREATE TABLE tb_tipo_resposta_ar (id NUMBER(10) NOT NULL, criado_por NUMBER(10) DEFAULT NULL NULL, atualizado_por NUMBER(10) DEFAULT NULL NULL, apagado_por NUMBER(10) DEFAULT NULL NULL, uuid CHAR(36) NOT NULL, ds_resposta_ar VARCHAR2(255) NOT NULL, criado_em TIMESTAMP(0) DEFAULT NULL NULL, atualizado_em TIMESTAMP(0) DEFAULT NULL NULL, apagado_em TIMESTAMP(0) DEFAULT NULL NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_B94F2182F69C7D9B ON tb_tipo_resposta_ar (criado_por)');
            $this->addSql('CREATE INDEX IDX_B94F2182AF2B1A92 ON tb_tipo_resposta_ar (atualizado_por)');
            $this->addSql('CREATE INDEX IDX_B94F2182A395BB94 ON tb_tipo_resposta_ar (apagado_por)');
            $this->addSql('CREATE INDEX IDX_B94F2182FF6A170EBF396750 ON tb_tipo_resposta_ar (apagado_em, id)');
            $this->addSql('COMMENT ON COLUMN tb_tipo_resposta_ar.uuid IS \'(DC2Type:guid)\'');

            $this->addSql('ALTER TABLE tb_arquivo ADD CONSTRAINT FK_F2AD2580F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_arquivo ADD CONSTRAINT FK_F2AD2580AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_arquivo ADD CONSTRAINT FK_F2AD2580A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_baixa_rastreamento ADD CONSTRAINT FK_23B01B22F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_baixa_rastreamento ADD CONSTRAINT FK_23B01B22AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_baixa_rastreamento ADD CONSTRAINT FK_23B01B22A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_cancelamento_lote ADD CONSTRAINT FK_5C50DC79B172197C FOREIGN KEY (lote_id) REFERENCES tb_lote (id)');
            $this->addSql('ALTER TABLE tb_cancelamento_lote ADD CONSTRAINT FK_5C50DC797E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_cancelamento_lote ADD CONSTRAINT FK_5C50DC79F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_cancelamento_lote ADD CONSTRAINT FK_5C50DC79AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_cancelamento_lote ADD CONSTRAINT FK_5C50DC79A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_devolucao_ar ADD CONSTRAINT FK_BF8E6E10B172197C FOREIGN KEY (lote_id) REFERENCES tb_lote (id)');
            $this->addSql('ALTER TABLE tb_devolucao_ar ADD CONSTRAINT FK_BF8E6E10C75BF859 FOREIGN KEY (documentos_id) REFERENCES ad_documento (id)');
            $this->addSql('ALTER TABLE tb_devolucao_ar ADD CONSTRAINT FK_BF8E6E1046E7720A FOREIGN KEY (baixa_rastreamento_id) REFERENCES tb_baixa_rastreamento (id)');
            $this->addSql('ALTER TABLE tb_devolucao_ar ADD CONSTRAINT FK_BF8E6E107E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_devolucao_ar ADD CONSTRAINT FK_BF8E6E10A924DC31 FOREIGN KEY (lote_devolucao_id) REFERENCES tb_lote_devolucao_ar (id)');
            $this->addSql('ALTER TABLE tb_devolucao_ar ADD CONSTRAINT FK_BF8E6E10F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_devolucao_ar ADD CONSTRAINT FK_BF8E6E10AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_devolucao_ar ADD CONSTRAINT FK_BF8E6E10A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_inconsistencia ADD CONSTRAINT FK_3A7A94BDBE86A4FA FOREIGN KEY (tipo_inconsistencia_id) REFERENCES tb_tipo_inconsistencia (id)');
            $this->addSql('ALTER TABLE tb_inconsistencia ADD CONSTRAINT FK_3A7A94BD7E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_inconsistencia ADD CONSTRAINT FK_3A7A94BDF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_inconsistencia ADD CONSTRAINT FK_3A7A94BDAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_inconsistencia ADD CONSTRAINT FK_3A7A94BDA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_lote ADD CONSTRAINT FK_3EC4308E3446B1F9 FOREIGN KEY (inconsistencia_id) REFERENCES tb_inconsistencia (id)');
            $this->addSql('ALTER TABLE tb_lote ADD CONSTRAINT FK_3EC4308E7E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_lote ADD CONSTRAINT FK_3EC4308EF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_lote ADD CONSTRAINT FK_3EC4308EAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_lote ADD CONSTRAINT FK_3EC4308EA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_lote_devolucao_ar ADD CONSTRAINT FK_AF552DE47E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_lote_devolucao_ar ADD CONSTRAINT FK_AF552DE4F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_lote_devolucao_ar ADD CONSTRAINT FK_AF552DE4AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_lote_devolucao_ar ADD CONSTRAINT FK_AF552DE4A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_recibo_servico ADD CONSTRAINT FK_90C1484AB172197C FOREIGN KEY (lote_id) REFERENCES tb_lote (id)');
            $this->addSql('ALTER TABLE tb_recibo_servico ADD CONSTRAINT FK_90C1484A7E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_recibo_servico ADD CONSTRAINT FK_90C1484AF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_recibo_servico ADD CONSTRAINT FK_90C1484AAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_recibo_servico ADD CONSTRAINT FK_90C1484AA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar ADD CONSTRAINT FK_C87DC95C1764677E FOREIGN KEY (lote_devolucao_ar_id) REFERENCES tb_lote_devolucao_ar (id)');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar ADD CONSTRAINT FK_C87DC95C7E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar ADD CONSTRAINT FK_C87DC95CF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar ADD CONSTRAINT FK_C87DC95CAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar ADD CONSTRAINT FK_C87DC95CA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resp_cancelamento ADD CONSTRAINT FK_1919680FB172197C FOREIGN KEY (lote_id) REFERENCES tb_lote (id)');
            $this->addSql('ALTER TABLE tb_resp_cancelamento ADD CONSTRAINT FK_1919680F7E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_resp_cancelamento ADD CONSTRAINT FK_1919680FF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resp_cancelamento ADD CONSTRAINT FK_1919680FAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resp_cancelamento ADD CONSTRAINT FK_1919680FA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resposta_ar ADD CONSTRAINT FK_2C4B1306B172197C FOREIGN KEY (lote_id) REFERENCES tb_lote (id)');
            $this->addSql('ALTER TABLE tb_resposta_ar ADD CONSTRAINT FK_2C4B13065E64109 FOREIGN KEY (tipo_resposta_ar_id) REFERENCES tb_tipo_resposta_ar (id)');
            $this->addSql('ALTER TABLE tb_resposta_ar ADD CONSTRAINT FK_2C4B13067E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_resposta_ar ADD CONSTRAINT FK_2C4B1306A924DC31 FOREIGN KEY (lote_devolucao_id) REFERENCES tb_lote_devolucao_ar (id)');
            $this->addSql('ALTER TABLE tb_resposta_ar ADD CONSTRAINT FK_2C4B1306F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resposta_ar ADD CONSTRAINT FK_2C4B1306AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resposta_ar ADD CONSTRAINT FK_2C4B1306A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resposta_notificacao ADD CONSTRAINT FK_3E98115B172197C FOREIGN KEY (lote_id) REFERENCES tb_lote (id)');
            $this->addSql('ALTER TABLE tb_resposta_notificacao ADD CONSTRAINT FK_3E981157E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_resposta_notificacao ADD CONSTRAINT FK_3E98115F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resposta_notificacao ADD CONSTRAINT FK_3E98115AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resposta_notificacao ADD CONSTRAINT FK_3E98115A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_servico_referencia ADD CONSTRAINT FK_584071C8B172197C FOREIGN KEY (lote_id) REFERENCES tb_lote (id)');
            $this->addSql('ALTER TABLE tb_servico_referencia ADD CONSTRAINT FK_584071C8F5F33411 FOREIGN KEY (recibo_servico_id) REFERENCES tb_recibo_servico (id)');
            $this->addSql('ALTER TABLE tb_servico_referencia ADD CONSTRAINT FK_584071C8187B6982 FOREIGN KEY (devolucao_ar_id) REFERENCES tb_devolucao_ar (id)');
            $this->addSql('ALTER TABLE tb_servico_referencia ADD CONSTRAINT FK_584071C889358EA9 FOREIGN KEY (resposta_ar_id) REFERENCES tb_resposta_ar (id)');
            $this->addSql('ALTER TABLE tb_servico_referencia ADD CONSTRAINT FK_584071C83446B1F9 FOREIGN KEY (inconsistencia_id) REFERENCES tb_inconsistencia (id)');
            $this->addSql('ALTER TABLE tb_servico_referencia ADD CONSTRAINT FK_584071C8F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_servico_referencia ADD CONSTRAINT FK_584071C8AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_servico_referencia ADD CONSTRAINT FK_584071C8A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_tipo_inconsistencia ADD CONSTRAINT FK_365BB71CF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_tipo_inconsistencia ADD CONSTRAINT FK_365BB71CAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_tipo_inconsistencia ADD CONSTRAINT FK_365BB71CA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_tipo_resposta_ar ADD CONSTRAINT FK_B94F2182F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_tipo_resposta_ar ADD CONSTRAINT FK_B94F2182AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_tipo_resposta_ar ADD CONSTRAINT FK_B94F2182A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
        } else {

            $this->addSql('ALTER TABLE tb_arquivo ADD CONSTRAINT FK_F2AD2580F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_arquivo ADD CONSTRAINT FK_F2AD2580AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_arquivo ADD CONSTRAINT FK_F2AD2580A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_baixa_rastreamento ADD CONSTRAINT FK_23B01B22F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_baixa_rastreamento ADD CONSTRAINT FK_23B01B22AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_baixa_rastreamento ADD CONSTRAINT FK_23B01B22A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_cancelamento_lote ADD CONSTRAINT FK_5C50DC79B172197C FOREIGN KEY (lote_id) REFERENCES tb_lote (id)');
            $this->addSql('ALTER TABLE tb_cancelamento_lote ADD CONSTRAINT FK_5C50DC797E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_cancelamento_lote ADD CONSTRAINT FK_5C50DC79F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_cancelamento_lote ADD CONSTRAINT FK_5C50DC79AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_cancelamento_lote ADD CONSTRAINT FK_5C50DC79A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_devolucao_ar ADD CONSTRAINT FK_BF8E6E10B172197C FOREIGN KEY (lote_id) REFERENCES tb_lote (id)');
            $this->addSql('ALTER TABLE tb_devolucao_ar ADD CONSTRAINT FK_BF8E6E10C75BF859 FOREIGN KEY (documentos_id) REFERENCES ad_documento (id)');
            $this->addSql('ALTER TABLE tb_devolucao_ar ADD CONSTRAINT FK_BF8E6E1046E7720A FOREIGN KEY (baixa_rastreamento_id) REFERENCES tb_baixa_rastreamento (id)');
            $this->addSql('ALTER TABLE tb_devolucao_ar ADD CONSTRAINT FK_BF8E6E107E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_devolucao_ar ADD CONSTRAINT FK_BF8E6E10A924DC31 FOREIGN KEY (lote_devolucao_id) REFERENCES tb_lote_devolucao_ar (id)');
            $this->addSql('ALTER TABLE tb_devolucao_ar ADD CONSTRAINT FK_BF8E6E10F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_devolucao_ar ADD CONSTRAINT FK_BF8E6E10AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_devolucao_ar ADD CONSTRAINT FK_BF8E6E10A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_inconsistencia ADD CONSTRAINT FK_3A7A94BDBE86A4FA FOREIGN KEY (tipo_inconsistencia_id) REFERENCES tb_tipo_inconsistencia (id)');
            $this->addSql('ALTER TABLE tb_inconsistencia ADD CONSTRAINT FK_3A7A94BD7E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_inconsistencia ADD CONSTRAINT FK_3A7A94BDF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_inconsistencia ADD CONSTRAINT FK_3A7A94BDAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_inconsistencia ADD CONSTRAINT FK_3A7A94BDA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_lote ADD CONSTRAINT FK_3EC4308E3446B1F9 FOREIGN KEY (inconsistencia_id) REFERENCES tb_inconsistencia (id)');
            $this->addSql('ALTER TABLE tb_lote ADD CONSTRAINT FK_3EC4308E7E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_lote ADD CONSTRAINT FK_3EC4308EF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_lote ADD CONSTRAINT FK_3EC4308EAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_lote ADD CONSTRAINT FK_3EC4308EA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_lote_devolucao_ar ADD CONSTRAINT FK_AF552DE47E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_lote_devolucao_ar ADD CONSTRAINT FK_AF552DE4F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_lote_devolucao_ar ADD CONSTRAINT FK_AF552DE4AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_lote_devolucao_ar ADD CONSTRAINT FK_AF552DE4A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_recibo_servico ADD CONSTRAINT FK_90C1484AB172197C FOREIGN KEY (lote_id) REFERENCES tb_lote (id)');
            $this->addSql('ALTER TABLE tb_recibo_servico ADD CONSTRAINT FK_90C1484A7E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_recibo_servico ADD CONSTRAINT FK_90C1484AF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_recibo_servico ADD CONSTRAINT FK_90C1484AAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_recibo_servico ADD CONSTRAINT FK_90C1484AA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar ADD CONSTRAINT FK_C87DC95C1764677E FOREIGN KEY (lote_devolucao_ar_id) REFERENCES tb_lote_devolucao_ar (id)');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar ADD CONSTRAINT FK_C87DC95C7E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar ADD CONSTRAINT FK_C87DC95CF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar ADD CONSTRAINT FK_C87DC95CAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar ADD CONSTRAINT FK_C87DC95CA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resp_cancelamento ADD CONSTRAINT FK_1919680FB172197C FOREIGN KEY (lote_id) REFERENCES tb_lote (id)');
            $this->addSql('ALTER TABLE tb_resp_cancelamento ADD CONSTRAINT FK_1919680F7E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_resp_cancelamento ADD CONSTRAINT FK_1919680FF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resp_cancelamento ADD CONSTRAINT FK_1919680FAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resp_cancelamento ADD CONSTRAINT FK_1919680FA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resposta_ar ADD CONSTRAINT FK_2C4B1306B172197C FOREIGN KEY (lote_id) REFERENCES tb_lote (id)');
            $this->addSql('ALTER TABLE tb_resposta_ar ADD CONSTRAINT FK_2C4B13065E64109 FOREIGN KEY (tipo_resposta_ar_id) REFERENCES tb_tipo_resposta_ar (id)');
            $this->addSql('ALTER TABLE tb_resposta_ar ADD CONSTRAINT FK_2C4B13067E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_resposta_ar ADD CONSTRAINT FK_2C4B1306A924DC31 FOREIGN KEY (lote_devolucao_id) REFERENCES tb_lote_devolucao_ar (id)');
            $this->addSql('ALTER TABLE tb_resposta_ar ADD CONSTRAINT FK_2C4B1306F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resposta_ar ADD CONSTRAINT FK_2C4B1306AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resposta_ar ADD CONSTRAINT FK_2C4B1306A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resposta_notificacao ADD CONSTRAINT FK_3E98115B172197C FOREIGN KEY (lote_id) REFERENCES tb_lote (id)');
            $this->addSql('ALTER TABLE tb_resposta_notificacao ADD CONSTRAINT FK_3E981157E7C3263 FOREIGN KEY (arquivo_id) REFERENCES tb_arquivo (id)');
            $this->addSql('ALTER TABLE tb_resposta_notificacao ADD CONSTRAINT FK_3E98115F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resposta_notificacao ADD CONSTRAINT FK_3E98115AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_resposta_notificacao ADD CONSTRAINT FK_3E98115A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_servico_referencia ADD CONSTRAINT FK_584071C8B172197C FOREIGN KEY (lote_id) REFERENCES tb_lote (id)');
            $this->addSql('ALTER TABLE tb_servico_referencia ADD CONSTRAINT FK_584071C8F5F33411 FOREIGN KEY (recibo_servico_id) REFERENCES tb_recibo_servico (id)');
            $this->addSql('ALTER TABLE tb_servico_referencia ADD CONSTRAINT FK_584071C8187B6982 FOREIGN KEY (devolucao_ar_id) REFERENCES tb_devolucao_ar (id)');
            $this->addSql('ALTER TABLE tb_servico_referencia ADD CONSTRAINT FK_584071C889358EA9 FOREIGN KEY (resposta_ar_id) REFERENCES tb_resposta_ar (id)');
            $this->addSql('ALTER TABLE tb_servico_referencia ADD CONSTRAINT FK_584071C83446B1F9 FOREIGN KEY (inconsistencia_id) REFERENCES tb_inconsistencia (id)');
            $this->addSql('ALTER TABLE tb_servico_referencia ADD CONSTRAINT FK_584071C8F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_servico_referencia ADD CONSTRAINT FK_584071C8AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_servico_referencia ADD CONSTRAINT FK_584071C8A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_tipo_inconsistencia ADD CONSTRAINT FK_365BB71CF69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_tipo_inconsistencia ADD CONSTRAINT FK_365BB71CAF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_tipo_inconsistencia ADD CONSTRAINT FK_365BB71CA395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_tipo_resposta_ar ADD CONSTRAINT FK_B94F2182F69C7D9B FOREIGN KEY (criado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_tipo_resposta_ar ADD CONSTRAINT FK_B94F2182AF2B1A92 FOREIGN KEY (atualizado_por) REFERENCES ad_usuario (id)');
            $this->addSql('ALTER TABLE tb_tipo_resposta_ar ADD CONSTRAINT FK_B94F2182A395BB94 FOREIGN KEY (apagado_por) REFERENCES ad_usuario (id)');
        }
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        if ('oracle' === $this->connection->getDatabasePlatform()->getName() ||
            'postgresql' === $this->connection->getDatabasePlatform()->getName()) {
            $this->addSql('DROP SEQUENCE tb_arquivo_id_seq');
            $this->addSql('DROP SEQUENCE tb_baixa_rastreamento_id_seq');
            $this->addSql('DROP SEQUENCE tb_cancelamento_lote_id_seq');
            $this->addSql('DROP SEQUENCE tb_devolucao_ar_id_seq');
            $this->addSql('DROP SEQUENCE tb_inconsistencia_id_seq');
            $this->addSql('DROP SEQUENCE tb_lote_id_seq');
            $this->addSql('DROP SEQUENCE tb_lote_devolucao_ar_id_seq');
            $this->addSql('DROP SEQUENCE tb_recibo_servico_id_seq');
            $this->addSql('DROP SEQUENCE tb_recusa_resposta_ar_id_seq');
            $this->addSql('DROP SEQUENCE tb_resp_cancelamento_id_seq');
            $this->addSql('DROP SEQUENCE tb_resposta_ar_id_seq');
            $this->addSql('DROP SEQUENCE tb_resposta_notificacao_id_seq');
            $this->addSql('DROP SEQUENCE tb_servico_referencia_id_seq');
            $this->addSql('DROP SEQUENCE tb_tipo_inconsistencia_id_seq');
            $this->addSql('DROP SEQUENCE tb_tipo_resposta_ar_id_seq');

            $this->addSql('ALTER TABLE tb_arquivo DROP CONSTRAINT FK_F2AD2580F69C7D9B');
            $this->addSql('ALTER TABLE tb_arquivo DROP CONSTRAINT FK_F2AD2580AF2B1A92');
            $this->addSql('ALTER TABLE tb_arquivo DROP CONSTRAINT FK_F2AD2580A395BB94');
            $this->addSql('ALTER TABLE tb_baixa_rastreamento DROP CONSTRAINT FK_23B01B22F69C7D9B');
            $this->addSql('ALTER TABLE tb_baixa_rastreamento DROP CONSTRAINT FK_23B01B22AF2B1A92');
            $this->addSql('ALTER TABLE tb_baixa_rastreamento DROP CONSTRAINT FK_23B01B22A395BB94');
            $this->addSql('ALTER TABLE tb_cancelamento_lote DROP CONSTRAINT FK_5C50DC79B172197C');
            $this->addSql('ALTER TABLE tb_cancelamento_lote DROP CONSTRAINT FK_5C50DC797E7C3263');
            $this->addSql('ALTER TABLE tb_cancelamento_lote DROP CONSTRAINT FK_5C50DC79F69C7D9B');
            $this->addSql('ALTER TABLE tb_cancelamento_lote DROP CONSTRAINT FK_5C50DC79AF2B1A92');
            $this->addSql('ALTER TABLE tb_cancelamento_lote DROP CONSTRAINT FK_5C50DC79A395BB94');
            $this->addSql('ALTER TABLE tb_devolucao_ar DROP CONSTRAINT FK_BF8E6E10B172197C');
            $this->addSql('ALTER TABLE tb_devolucao_ar DROP CONSTRAINT FK_BF8E6E10C75BF859');
            $this->addSql('ALTER TABLE tb_devolucao_ar DROP CONSTRAINT FK_BF8E6E1046E7720A');
            $this->addSql('ALTER TABLE tb_devolucao_ar DROP CONSTRAINT FK_BF8E6E107E7C3263');
            $this->addSql('ALTER TABLE tb_devolucao_ar DROP CONSTRAINT FK_BF8E6E10A924DC31');
            $this->addSql('ALTER TABLE tb_devolucao_ar DROP CONSTRAINT FK_BF8E6E10F69C7D9B');
            $this->addSql('ALTER TABLE tb_devolucao_ar DROP CONSTRAINT FK_BF8E6E10AF2B1A92');
            $this->addSql('ALTER TABLE tb_devolucao_ar DROP CONSTRAINT FK_BF8E6E10A395BB94');
            $this->addSql('ALTER TABLE tb_inconsistencia DROP CONSTRAINT FK_3A7A94BDBE86A4FA');
            $this->addSql('ALTER TABLE tb_inconsistencia DROP CONSTRAINT FK_3A7A94BD7E7C3263');
            $this->addSql('ALTER TABLE tb_inconsistencia DROP CONSTRAINT FK_3A7A94BDF69C7D9B');
            $this->addSql('ALTER TABLE tb_inconsistencia DROP CONSTRAINT FK_3A7A94BDAF2B1A92');
            $this->addSql('ALTER TABLE tb_inconsistencia DROP CONSTRAINT FK_3A7A94BDA395BB94');
            $this->addSql('ALTER TABLE tb_lote DROP CONSTRAINT FK_3EC4308E3446B1F9');
            $this->addSql('ALTER TABLE tb_lote DROP CONSTRAINT FK_3EC4308E7E7C3263');
            $this->addSql('ALTER TABLE tb_lote DROP CONSTRAINT FK_3EC4308EF69C7D9B');
            $this->addSql('ALTER TABLE tb_lote DROP CONSTRAINT FK_3EC4308EAF2B1A92');
            $this->addSql('ALTER TABLE tb_lote DROP CONSTRAINT FK_3EC4308EA395BB94');
            $this->addSql('ALTER TABLE tb_lote_devolucao_ar DROP CONSTRAINT FK_AF552DE47E7C3263');
            $this->addSql('ALTER TABLE tb_lote_devolucao_ar DROP CONSTRAINT FK_AF552DE4F69C7D9B');
            $this->addSql('ALTER TABLE tb_lote_devolucao_ar DROP CONSTRAINT FK_AF552DE4AF2B1A92');
            $this->addSql('ALTER TABLE tb_lote_devolucao_ar DROP CONSTRAINT FK_AF552DE4A395BB94');
            $this->addSql('ALTER TABLE tb_recibo_servico DROP CONSTRAINT FK_90C1484AB172197C');
            $this->addSql('ALTER TABLE tb_recibo_servico DROP CONSTRAINT FK_90C1484A7E7C3263');
            $this->addSql('ALTER TABLE tb_recibo_servico DROP CONSTRAINT FK_90C1484AF69C7D9B');
            $this->addSql('ALTER TABLE tb_recibo_servico DROP CONSTRAINT FK_90C1484AAF2B1A92');
            $this->addSql('ALTER TABLE tb_recibo_servico DROP CONSTRAINT FK_90C1484AA395BB94');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar DROP CONSTRAINT FK_C87DC95C1764677E');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar DROP CONSTRAINT FK_C87DC95C7E7C3263');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar DROP CONSTRAINT FK_C87DC95CF69C7D9B');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar DROP CONSTRAINT FK_C87DC95CAF2B1A92');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar DROP CONSTRAINT FK_C87DC95CA395BB94');
            $this->addSql('ALTER TABLE tb_resp_cancelamento DROP CONSTRAINT FK_1919680FB172197C');
            $this->addSql('ALTER TABLE tb_resp_cancelamento DROP CONSTRAINT FK_1919680F7E7C3263');
            $this->addSql('ALTER TABLE tb_resp_cancelamento DROP CONSTRAINT FK_1919680FF69C7D9B');
            $this->addSql('ALTER TABLE tb_resp_cancelamento DROP CONSTRAINT FK_1919680FAF2B1A92');
            $this->addSql('ALTER TABLE tb_resp_cancelamento DROP CONSTRAINT FK_1919680FA395BB94');
            $this->addSql('ALTER TABLE tb_resposta_ar DROP CONSTRAINT FK_2C4B1306B172197C');
            $this->addSql('ALTER TABLE tb_resposta_ar DROP CONSTRAINT FK_2C4B13065E64109');
            $this->addSql('ALTER TABLE tb_resposta_ar DROP CONSTRAINT FK_2C4B13067E7C3263');
            $this->addSql('ALTER TABLE tb_resposta_ar DROP CONSTRAINT FK_2C4B1306A924DC31');
            $this->addSql('ALTER TABLE tb_resposta_ar DROP CONSTRAINT FK_2C4B1306F69C7D9B');
            $this->addSql('ALTER TABLE tb_resposta_ar DROP CONSTRAINT FK_2C4B1306AF2B1A92');
            $this->addSql('ALTER TABLE tb_resposta_ar DROP CONSTRAINT FK_2C4B1306A395BB94');
            $this->addSql('ALTER TABLE tb_resposta_notificacao DROP CONSTRAINT FK_3E98115B172197C');
            $this->addSql('ALTER TABLE tb_resposta_notificacao DROP CONSTRAINT FK_3E981157E7C3263');
            $this->addSql('ALTER TABLE tb_resposta_notificacao DROP CONSTRAINT FK_3E98115F69C7D9B');
            $this->addSql('ALTER TABLE tb_resposta_notificacao DROP CONSTRAINT FK_3E98115AF2B1A92');
            $this->addSql('ALTER TABLE tb_resposta_notificacao DROP CONSTRAINT FK_3E98115A395BB94');
            $this->addSql('ALTER TABLE tb_servico_referencia DROP CONSTRAINT FK_584071C8B172197C');
            $this->addSql('ALTER TABLE tb_servico_referencia DROP CONSTRAINT FK_584071C8F5F33411');
            $this->addSql('ALTER TABLE tb_servico_referencia DROP CONSTRAINT FK_584071C8187B6982');
            $this->addSql('ALTER TABLE tb_servico_referencia DROP CONSTRAINT FK_584071C889358EA9');
            $this->addSql('ALTER TABLE tb_servico_referencia DROP CONSTRAINT FK_584071C83446B1F9');
            $this->addSql('ALTER TABLE tb_servico_referencia DROP CONSTRAINT FK_584071C8F69C7D9B');
            $this->addSql('ALTER TABLE tb_servico_referencia DROP CONSTRAINT FK_584071C8AF2B1A92');
            $this->addSql('ALTER TABLE tb_servico_referencia DROP CONSTRAINT FK_584071C8A395BB94');
            $this->addSql('ALTER TABLE tb_tipo_inconsistencia DROP CONSTRAINT FK_365BB71CF69C7D9B');
            $this->addSql('ALTER TABLE tb_tipo_inconsistencia DROP CONSTRAINT FK_365BB71CAF2B1A92');
            $this->addSql('ALTER TABLE tb_tipo_inconsistencia DROP CONSTRAINT FK_365BB71CA395BB94');
            $this->addSql('ALTER TABLE tb_tipo_resposta_ar DROP CONSTRAINT FK_B94F2182F69C7D9B');
            $this->addSql('ALTER TABLE tb_tipo_resposta_ar DROP CONSTRAINT FK_B94F2182AF2B1A92');
            $this->addSql('ALTER TABLE tb_tipo_resposta_ar DROP CONSTRAINT FK_B94F2182A395BB94');

            $this->addSql('DROP TABLE tb_arquivo');
            $this->addSql('DROP TABLE tb_baixa_rastreamento');
            $this->addSql('DROP TABLE tb_cancelamento_lote');
            $this->addSql('DROP TABLE tb_devolucao_ar');
            $this->addSql('DROP TABLE tb_inconsistencia');
            $this->addSql('DROP TABLE tb_lote');
            $this->addSql('DROP TABLE tb_lote_devolucao_ar');
            $this->addSql('DROP TABLE tb_recibo_servico');
            $this->addSql('DROP TABLE tb_recusa_resposta_ar');
            $this->addSql('DROP TABLE tb_resp_cancelamento');
            $this->addSql('DROP TABLE tb_resposta_ar');
            $this->addSql('DROP TABLE tb_resposta_notificacao');
            $this->addSql('DROP TABLE tb_servico_referencia');
            $this->addSql('DROP TABLE tb_tipo_inconsistencia');
            $this->addSql('DROP TABLE tb_tipo_resposta_ar');
        } else {

            $this->addSql('ALTER TABLE tb_arquivo DROP FOREIGN KEY FK_F2AD2580F69C7D9B');
            $this->addSql('ALTER TABLE tb_arquivo DROP FOREIGN KEY FK_F2AD2580AF2B1A92');
            $this->addSql('ALTER TABLE tb_arquivo DROP FOREIGN KEY FK_F2AD2580A395BB94');
            $this->addSql('ALTER TABLE tb_baixa_rastreamento DROP FOREIGN KEY FK_23B01B22F69C7D9B');
            $this->addSql('ALTER TABLE tb_baixa_rastreamento DROP FOREIGN KEY FK_23B01B22AF2B1A92');
            $this->addSql('ALTER TABLE tb_baixa_rastreamento DROP FOREIGN KEY FK_23B01B22A395BB94');
            $this->addSql('ALTER TABLE tb_cancelamento_lote DROP FOREIGN KEY FK_5C50DC79B172197C');
            $this->addSql('ALTER TABLE tb_cancelamento_lote DROP FOREIGN KEY FK_5C50DC797E7C3263');
            $this->addSql('ALTER TABLE tb_cancelamento_lote DROP FOREIGN KEY FK_5C50DC79F69C7D9B');
            $this->addSql('ALTER TABLE tb_cancelamento_lote DROP FOREIGN KEY FK_5C50DC79AF2B1A92');
            $this->addSql('ALTER TABLE tb_cancelamento_lote DROP FOREIGN KEY FK_5C50DC79A395BB94');
            $this->addSql('ALTER TABLE tb_devolucao_ar DROP FOREIGN KEY FK_BF8E6E10B172197C');
            $this->addSql('ALTER TABLE tb_devolucao_ar DROP FOREIGN KEY FK_BF8E6E10C75BF859');
            $this->addSql('ALTER TABLE tb_devolucao_ar DROP FOREIGN KEY FK_BF8E6E1046E7720A');
            $this->addSql('ALTER TABLE tb_devolucao_ar DROP FOREIGN KEY FK_BF8E6E107E7C3263');
            $this->addSql('ALTER TABLE tb_devolucao_ar DROP FOREIGN KEY FK_BF8E6E10A924DC31');
            $this->addSql('ALTER TABLE tb_devolucao_ar DROP FOREIGN KEY FK_BF8E6E10F69C7D9B');
            $this->addSql('ALTER TABLE tb_devolucao_ar DROP FOREIGN KEY FK_BF8E6E10AF2B1A92');
            $this->addSql('ALTER TABLE tb_devolucao_ar DROP FOREIGN KEY FK_BF8E6E10A395BB94');
            $this->addSql('ALTER TABLE tb_inconsistencia DROP FOREIGN KEY FK_3A7A94BDBE86A4FA');
            $this->addSql('ALTER TABLE tb_inconsistencia DROP FOREIGN KEY FK_3A7A94BD7E7C3263');
            $this->addSql('ALTER TABLE tb_inconsistencia DROP FOREIGN KEY FK_3A7A94BDF69C7D9B');
            $this->addSql('ALTER TABLE tb_inconsistencia DROP FOREIGN KEY FK_3A7A94BDAF2B1A92');
            $this->addSql('ALTER TABLE tb_inconsistencia DROP FOREIGN KEY FK_3A7A94BDA395BB94');
            $this->addSql('ALTER TABLE tb_lote DROP FOREIGN KEY FK_3EC4308E3446B1F9');
            $this->addSql('ALTER TABLE tb_lote DROP FOREIGN KEY FK_3EC4308E7E7C3263');
            $this->addSql('ALTER TABLE tb_lote DROP FOREIGN KEY FK_3EC4308EF69C7D9B');
            $this->addSql('ALTER TABLE tb_lote DROP FOREIGN KEY FK_3EC4308EAF2B1A92');
            $this->addSql('ALTER TABLE tb_lote DROP FOREIGN KEY FK_3EC4308EA395BB94');
            $this->addSql('ALTER TABLE tb_lote_devolucao_ar DROP FOREIGN KEY FK_AF552DE47E7C3263');
            $this->addSql('ALTER TABLE tb_lote_devolucao_ar DROP FOREIGN KEY FK_AF552DE4F69C7D9B');
            $this->addSql('ALTER TABLE tb_lote_devolucao_ar DROP FOREIGN KEY FK_AF552DE4AF2B1A92');
            $this->addSql('ALTER TABLE tb_lote_devolucao_ar DROP FOREIGN KEY FK_AF552DE4A395BB94');
            $this->addSql('ALTER TABLE tb_recibo_servico DROP FOREIGN KEY FK_90C1484AB172197C');
            $this->addSql('ALTER TABLE tb_recibo_servico DROP FOREIGN KEY FK_90C1484A7E7C3263');
            $this->addSql('ALTER TABLE tb_recibo_servico DROP FOREIGN KEY FK_90C1484AF69C7D9B');
            $this->addSql('ALTER TABLE tb_recibo_servico DROP FOREIGN KEY FK_90C1484AAF2B1A92');
            $this->addSql('ALTER TABLE tb_recibo_servico DROP FOREIGN KEY FK_90C1484AA395BB94');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar DROP FOREIGN KEY FK_C87DC95C1764677E');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar DROP FOREIGN KEY FK_C87DC95C7E7C3263');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar DROP FOREIGN KEY FK_C87DC95CF69C7D9B');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar DROP FOREIGN KEY FK_C87DC95CAF2B1A92');
            $this->addSql('ALTER TABLE tb_recusa_resposta_ar DROP FOREIGN KEY FK_C87DC95CA395BB94');
            $this->addSql('ALTER TABLE tb_resp_cancelamento DROP FOREIGN KEY FK_1919680FB172197C');
            $this->addSql('ALTER TABLE tb_resp_cancelamento DROP FOREIGN KEY FK_1919680F7E7C3263');
            $this->addSql('ALTER TABLE tb_resp_cancelamento DROP FOREIGN KEY FK_1919680FF69C7D9B');
            $this->addSql('ALTER TABLE tb_resp_cancelamento DROP FOREIGN KEY FK_1919680FAF2B1A92');
            $this->addSql('ALTER TABLE tb_resp_cancelamento DROP FOREIGN KEY FK_1919680FA395BB94');
            $this->addSql('ALTER TABLE tb_resposta_ar DROP FOREIGN KEY FK_2C4B1306B172197C');
            $this->addSql('ALTER TABLE tb_resposta_ar DROP FOREIGN KEY FK_2C4B13065E64109');
            $this->addSql('ALTER TABLE tb_resposta_ar DROP FOREIGN KEY FK_2C4B13067E7C3263');
            $this->addSql('ALTER TABLE tb_resposta_ar DROP FOREIGN KEY FK_2C4B1306A924DC31');
            $this->addSql('ALTER TABLE tb_resposta_ar DROP FOREIGN KEY FK_2C4B1306F69C7D9B');
            $this->addSql('ALTER TABLE tb_resposta_ar DROP FOREIGN KEY FK_2C4B1306AF2B1A92');
            $this->addSql('ALTER TABLE tb_resposta_ar DROP FOREIGN KEY FK_2C4B1306A395BB94');
            $this->addSql('ALTER TABLE tb_resposta_notificacao DROP FOREIGN KEY FK_3E98115B172197C');
            $this->addSql('ALTER TABLE tb_resposta_notificacao DROP FOREIGN KEY FK_3E981157E7C3263');
            $this->addSql('ALTER TABLE tb_resposta_notificacao DROP FOREIGN KEY FK_3E98115F69C7D9B');
            $this->addSql('ALTER TABLE tb_resposta_notificacao DROP FOREIGN KEY FK_3E98115AF2B1A92');
            $this->addSql('ALTER TABLE tb_resposta_notificacao DROP FOREIGN KEY FK_3E98115A395BB94');
            $this->addSql('ALTER TABLE tb_servico_referencia DROP FOREIGN KEY FK_584071C8B172197C');
            $this->addSql('ALTER TABLE tb_servico_referencia DROP FOREIGN KEY FK_584071C8F5F33411');
            $this->addSql('ALTER TABLE tb_servico_referencia DROP FOREIGN KEY FK_584071C8187B6982');
            $this->addSql('ALTER TABLE tb_servico_referencia DROP FOREIGN KEY FK_584071C889358EA9');
            $this->addSql('ALTER TABLE tb_servico_referencia DROP FOREIGN KEY FK_584071C83446B1F9');
            $this->addSql('ALTER TABLE tb_servico_referencia DROP FOREIGN KEY FK_584071C8F69C7D9B');
            $this->addSql('ALTER TABLE tb_servico_referencia DROP FOREIGN KEY FK_584071C8AF2B1A92');
            $this->addSql('ALTER TABLE tb_servico_referencia DROP FOREIGN KEY FK_584071C8A395BB94');
            $this->addSql('ALTER TABLE tb_tipo_inconsistencia DROP FOREIGN KEY FK_365BB71CF69C7D9B');
            $this->addSql('ALTER TABLE tb_tipo_inconsistencia DROP FOREIGN KEY FK_365BB71CAF2B1A92');
            $this->addSql('ALTER TABLE tb_tipo_inconsistencia DROP FOREIGN KEY FK_365BB71CA395BB94');
            $this->addSql('ALTER TABLE tb_tipo_resposta_ar DROP FOREIGN KEY FK_B94F2182F69C7D9B');
            $this->addSql('ALTER TABLE tb_tipo_resposta_ar DROP FOREIGN KEY FK_B94F2182AF2B1A92');
            $this->addSql('ALTER TABLE tb_tipo_resposta_ar DROP FOREIGN KEY FK_B94F2182A395BB94');
            $this->addSql('DROP TABLE tb_arquivo');
            $this->addSql('DROP TABLE tb_baixa_rastreamento');
            $this->addSql('DROP TABLE tb_cancelamento_lote');
            $this->addSql('DROP TABLE tb_devolucao_ar');
            $this->addSql('DROP TABLE tb_inconsistencia');
            $this->addSql('DROP TABLE tb_lote');
            $this->addSql('DROP TABLE tb_lote_devolucao_ar');
            $this->addSql('DROP TABLE tb_recibo_servico');
            $this->addSql('DROP TABLE tb_recusa_resposta_ar');
            $this->addSql('DROP TABLE tb_resp_cancelamento');
            $this->addSql('DROP TABLE tb_resposta_ar');
            $this->addSql('DROP TABLE tb_resposta_notificacao');
            $this->addSql('DROP TABLE tb_servico_referencia');
            $this->addSql('DROP TABLE tb_tipo_inconsistencia');
            $this->addSql('DROP TABLE tb_tipo_resposta_ar');
        }
    }
}
